### ISSUE TITLE
[Bug] Terra Classic bridge be reopened, when?

### ISSUE THREAD

**Issue by eliiik** [wormhole-foundation/wormhole-connect#1431] opened 2024-01-08 06:47 UTC
It's been a while since I see the repair branch been merged into the main branch. When can we expect the fixing go live in Wormhole website so that we can finnally get our tokens back from the bridge. It's been quite a long time.

**Comment by tonyjin** [comment] 2024-02-01 01:09
Dupe of https://github.com/wormhole-foundation/wormhole/issues/3633, which is resolved.

**Closed as completed by tonyjin** 2024-02-01 01:09 UTC
Labels: bug, integration-support
