### ISSUE TITLE
[QA] [Mobile] Missing Arbitrum Goerli network icon

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1306] opened 2023-12-07 09:00 UTC
Preconditions: None

Environment: iPhone 14, iOS 16, Safari

Tested from: https://wormhole-connect.netlify.app/

Steps:
1. Click on Connect network
2. Scroll the list till Arbitrum Goerli
3. Observe

Actual result: Arbitrum Goerli missing network icon

Expected result: All networks have corresponding wallet icons

Attachment:
![File_000](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4a94a2b5-9d5b-495d-9c73-a77c57ce58e9)

**Comment by tsadovska** [comment] 2024-02-12 10:56
Issue is also reproducible with "Arbitrum Sepolia" network. Checked on https://wormhole-connect.netlify.app/ [Testnet] with iOS 16.5.1 and Google Chrome Version 114.0.5735.124. Linked issue: https://github.com/wormhole-foundation/wormhole-connect/issues/1614.

![IMG_49AA1B60592A-1](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0bd9e154-f270-4b48-a51e-d7dd01d68056)

**Comment by tsadovska** [comment] 2024-06-04 11:51
Reproducible on https://preview.portalbridge.com/ac15114854/ [Mainnet]. Arbitrum icon is not displayed. Checked with iPhone 11 Pro and Google Chrome 125.0.6422.80.

**Comment by tsadovska** [comment] 2024-08-19 14:06
Closing as duplicate of https://github.com/wormhole-foundation/wormhole-connect/issues/2370

**Closed as not planned by tsadovska** 2024-08-19 14:06 UTC
Labels: p2
