### ISSUE TITLE
[QA] [OneKay wallet] Wallet pop-up shows no fee, cannot Sign transaction

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1989] opened 2024-04-23 11:48 UTC
Precondition:
OneKey wallet connected at sending From section
Phantom wallet connected at sending To section

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://portalbridge.com/

Steps:
1. Prepare to send 0.001 WMATIC from Osmosis to Solana
2. Click Approve and proceed with transaction
3. Observe wallet pop-up

Actual result: Wallet pop-up shows "No Available fee", only Cancel option is active on the pop-up message

Expected result: User is able to Confirm the transaction

Comments: OneKey wallet had enough asset available for gas fee

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bceeb23b-3c40-4054-8dc5-a3f95fbb2f1c

**Comment by tsadovska** [comment] 2024-05-27 08:48
Reproducible on [mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJCO4plGboWIRcIybhnzF3ERzTQ0mwWB1yYigOoBlAPIAZS2AC%2BIT0A%3D) when sending 0.0001 WSOL from Osmosis (OneKey wallet) to Solana (Phantom). "Sign" button on OneKey wallet notification is unclickable. 

![Screenshot 2024-05-27 at 11 44 54](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/8e4e4bda-5949-486b-bb98-97e365199083)

**Comment by tsadovska** [comment] 2024-07-31 14:10
Reproducible on https://portalbridge.com/ [Mainnet]. "Sign" button on OneKey wallet notification is unclickable. There are enough funds in the wallet to pay the fee - 5.495704 OSMO ($2.55). 

![image](https://github.com/user-attachments/assets/3c56dac6-24bf-41ef-9a35-e8a17a6453c4)


![Screenshot 2024-07-31 at 17 06 57](https://github.com/user-attachments/assets/e5ada76f-16fd-4096-9e5d-19889aed71b5)

**Comment by tsadovska** [comment] 2024-10-10 07:19
Closing the ticket because Cosmos chains are currently not displayed in the Networks list.

**Closed as not planned by tsadovska** 2024-10-10 07:19 UTC
Labels: p1, wallet
