### ISSUE TITLE
[QA] Negative Source chain gas estimate is shown

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2261] opened 2024-07-18 09:32 UTC
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/3365c86aff/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 126.0.6478.127 (Official Build) (arm64).

Steps:
1. Prepare to send 0.001 USDC.e from Fantom (MetaMask) to Ethereum (MetaMask)
2. Select "Native Token Transfers (NTT) Receive tokens automatically" route
3. Check "Source chain gas estimate" in Preview section

Actual result: Negative Source chain gas estimate is shown. 
Expected result: Source chain gas estimate is not a negative value. 

## Notes/ Attachments

![Screenshot 2024-07-18 at 12 31 13](https://github.com/user-attachments/assets/69ae94b5-47e9-4693-bf3b-6b065ab60185)

**Comment by agodlevska** [comment] 2024-08-29 16:06
Checked on https://portalbridge.com/. 

The issue is no longer present and now the '~' sign is displayed in the same place, which means 'approximately'.
Closing the ticket.

Attachment:
<img width="1278" alt="Screenshot 2024-08-29 at 19 03 42" src="https://github.com/user-attachments/assets/1df533be-5eed-44fe-abb5-51065183f60f">

**Closed as completed by agodlevska** 2024-08-29 16:06 UTC
Labels: p2
