### ISSUE TITLE
[QA] [Testnet] Transaction from Sei network fails

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1452] opened 2024-01-10 13:07 UTC
Preconditions:
Sei supported wallet connected at sending From section (Fin/Leap)
Metamask wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.129

Tested from: https://wormhole-connect.netlify.app/# 

Steps:
1. Prepare to send 0.1 SEI from Sei to Moonbase
2. Click Approve and proceed with transaction
3. Observe

Actual result: Transaction fails, reason `Error: Sei transaction failed with code 29. Log: failed to execute message; message index: 1: dispatch: submessages: dispatch: submessages: cannot send packet using client (07-tendermint-117) with status Expired: client is not active`

Expected result: Transaction is confirmed and completed

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6509317f-fcd1-4023-8652-c189c6eed1e4

![Screenshot 2024-01-10 at 15 02 41](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/687b6651-e712-4935-bc3a-5a0fc8d142fc)

**Comment by tsadovska** [comment] 2024-01-15 14:16
Closing as duplicate of https://github.com/wormhole-foundation/wormhole-connect/issues/762.

**Closed as not planned by tsadovska** 2024-01-15 14:16 UTC
Labels: p1
