### ISSUE TITLE
[QA] Balance is not loading for Solana wallets

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#817] opened 2023-08-09 10:26 UTC
## Describe the current behavior in detail
Balance is not loading when any Solana wallet is connected.

Tested from https://base-relayer--wormhole-connect.netlify.app/ [Testnet] with macOS Monterey 12.6.7 and Chrome Version 115.0.5790.170 (Official Build) (x86_64).

Steps:
1. Connect Solana network in 'From' section
2. Connect Phantom/Solflare/Slope/Exodus wallet in 'From' section
3. Open Asset list
4. Observe

Error is displayed in Console:
`Uncaught (in promise) Error: 429 :  {"jsonrpc":"2.0","error":{"code": 429, "message":"Too many requests for a specific RPC call, contact your app developer or support@rpcpool.com."}, "id": "be2a252f-94a8-4cc1-b10f-47997221a02f" } `

![Screenshot 2023-08-09 at 13 25 09](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b2ee023a-d66f-47a9-b395-220412a66e3b)

## What is the expected/desired behavior
Balance is shown.

**Comment by tsadovska** [comment] 2023-08-18 13:14
Issue is reproducible on https://base-relayer--wormhole-connect.netlify.app/ [Testnet].
Issue is not reproducible on:
- https://wormhole-connect.netlify.app/ [Testnet]
- https://mainnet--wormhole-connect.netlify.app/ [Mainnet]

**Comment by tsadovska** [comment] 2023-09-25 09:54
Rechecked the issue. It is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet] and https://mainnet--wormhole-connect.netlify.app/ [Mainnet].

Ticket is closed.

**Comment by agodlevska** [comment] 2024-07-01 13:36
Reopening the issue. 
Checked on https://wormhole-connect.netlify.app/ with macOS Sonoma 14.5 and Chrome Version 126.0.6478.127 (Official Build) (x86_64).

Balance is not loading for Solana network on Testnet. 

```
Failed to get token balances 
Error: 503 : {"jsonrpc":"2.0","error":{"code":503,"message":"Service unavailable"}, 
"id": null}
     
     at ClientBrowser.callServer
``` 
```
Failed to get native balance Error: failed to get balance of account A4xMgXFWpSAA4aG3Beo4Nxe9fvEvcs43i4czrMki79F3: Error: 503 : {"jsonrpc":"2.0","error":{"code":503,"message":"Service unavailable"}, "id": null}

    at main-Cubx2sfv.js:344:49960
    at async Connection$1.getBalance (main-Cubx2sfv.js:344:49885)
    at async SolanaContext.getNativeBalance (main-Cubx2sfv.js:498:191514)
    at async WormholeContext.getNativeBalance (main-Cubx2sfv.js:501:626925)
    at async main-Cubx2sfv.js:547:73249
``` 

Attachment:
<img width="1440" alt="Screenshot 2024-07-01 at 16 34 46" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/a3d6a2b9-2788-4490-b8a9-cc06fa72e6ae">

**Comment by agodlevska** [comment] 2024-07-31 07:19
The issue is no longer reproducible on https://wormhole-connect.netlify.app/ and https://wormhole-connect-mainnet.netlify.app/. 

Closing the ticket. 

Attachment: 

https://github.com/user-attachments/assets/0eba0fb8-bdb9-42a6-b843-8276a7174088

**Closed as completed by agodlevska** 2024-07-31 07:19 UTC
Labels: p1
