### ISSUE TITLE
[QA] Transaction is displayed in In-progress widget after it has been completed - CCTPRoute

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2760] opened 2024-09-27 09:00 UTC
## Describe the current behavior in detail
Reproducible on [wormhole-connect](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgEQFsCGAlpDLFgDThjKICus0AzpgNoDCrAKgAoBKt9AXRABfIA%3D%3D%3D) and https://preview.portalbridge.com/712d941311/. 
* Portal Bridge: v0.2.15-P33f1bcea4a
* Wormhole connect: v^1.0.0-beta.5-development

Steps:
1. Send 0.0001 USDC from Arbitrum (MetaMask) to Ethereum (MetaMask) with CCTPRoute
2. Check if In-progress widget is displayed after transfer has been completed

Actual result: Transaction is displayed in In-progress widget. 
Expected result: Transaction is no longer displayed in In-progress widget. 

## Notes/ Attachments
Link to [Wormholescan](https://wormholescan.io/#/tx/0x83c9716a7aeed854afcd4e6bfa4022fd0a7cb25830e3f61a6737fb1701f70565).

https://github.com/user-attachments/assets/8a7ef788-8b34-4035-a624-4b6c1c34dd46

**Comment by emreboga** [comment] 2024-09-30 12:54
This is probably waiting for the API response to update the status in the widget. I'll poll every 5 seconds until it receives the completed status.
@Wesleyleung this might be one of a fine tuning we need to make to the widget for a better UX ✌️

**Comment by tsadovska** [comment] 2024-09-30 15:28
I have 3 transactions in progress on https://wormhole-connect-mainnet.netlify.app/?config=N4KAdgpgLg7g9gJwNYC4AEAiAsgQwJZiRQYA0ICcArlBAM7oDaAwkwCoAKASlTQLogBfIA%3D%3D. 
Browser is making these requests every 5 seconds:
- https://api.wormholescan.io/api/v1/operations?txHash=0x5a7330a900a9fff2f442bdb4e9237b0878ddcd6e6e4fe018c824dfb2e112abd3
- https://api.wormholescan.io/api/v1/operations?txHash=0x3468222d0397988940cba35022c4a00ddeb9fbb9a00d8f79a6b97967cd9c4e29
- https://api.wormholescan.io/api/v1/operations?txHash=0x2f23f3d897da8dca39216d896eee4fd41f7dc9793f8c5a169e47936fef6876b1

Maybe you could check why these transactions have not completed?
* https://wormholescan.io/#/tx/0x2f23f3d897da8dca39216d896eee4fd41f7dc9793f8c5a169e47936fef6876b1 - started at Sep 27 18:11
* https://wormholescan.io/#/tx/0x5a7330a900a9fff2f442bdb4e9237b0878ddcd6e6e4fe018c824dfb2e112abd3
* https://wormholescan.io/#/tx/0x3468222d0397988940cba35022c4a00ddeb9fbb9a00d8f79a6b97967cd9c4e29

![image](https://github.com/user-attachments/assets/043adc27-5a4c-44d9-9091-55f99bb00fef)

**Comment by emreboga** [comment] 2024-09-30 15:31
To be more accurate, the widget is not showing the transaction in-progress. The widget itself is still in loading state fetching the data. In-progress transactions has the ETA countdown. The issue here should be the latency in the API response and how we react to that in the UX.
@tsadovska how long have you waited for the widget to complete the loading state?

**Comment by emreboga** [comment] 2024-09-30 15:49
@tsadovska never mind, I see the problem now. This is a manual transaction, and it seems the WHScan API doesn't return manual transactions. Let me check this with the WHExplorer team first.

**Comment by tsadovska** [comment] 2024-10-03 12:36
@emreboga I waited 19 minutes after the transaction was shown as completed on the destination chain in the Blockchain explorer. Despite the 19-minute wait, the completed transaction is still displayed in the In-progress widget. I also attempted to reload the page and resume the transfer, but widget was still loading. Checked on Oct 3 on https://portalbridge.com/. I sent 0.0001 USDC from Arbitrum (MetaMask) to Ethereum (MetaMask) with CCTPRoute.
* Source chain tx: [Arbiscan](https://arbiscan.io/tx/0x88497f039730c6ead844eb2e84d01da446f5a60d270c883c215363852dcb6042)
* Destination chain tx: [Etherscan](https://etherscan.io/tx/0x44bb573425031911f898bd70d823cfd9f4b0eeccc789426122f772cb1d97bdfe)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x88497f039730c6ead844eb2e84d01da446f5a60d270c883c215363852dcb6042)


https://github.com/user-attachments/assets/813f8279-0d7a-4b7c-ad64-015475232e6b




Issue https://github.com/wormhole-foundation/wormhole-connect/issues/2796 blocks checking the [original scenario](https://github.com/wormhole-foundation/wormhole-connect/issues/2760#issue-2552397880) on https://wormhole-connect-mainnet.netlify.app/.

**Comment by emreboga** [comment] 2024-10-03 13:10
@tsadovska I've confirmed with the WHScan team that manual transactions are not returned in the API response. At this moment we added a config prop to hide in-progress widgets by default. As a solution in the short-term, for manual transactions, we will probably will not show the widget.
Cc: @Wesleyleung

**Comment by Wesleyleung** [comment] 2024-10-03 18:15
@tsadovska can you confirm this issue only happens with USDC manual txns? I believe other manual txns should behave normally.

**Comment by tsadovska** [comment] 2024-10-03 18:48
@Wesleyleung Yes, issue is happening only with CCTPRoute.
I could not reproduce the issue using TokenBridgeRoute.
Checked following transactions using TokenBridgeRoute on https://portalbridge.com/ on Oct 3:
* 0.001 CELO transfer from Sui (Sui wallet) to Celo (MetaMask), link to [Wormholescan](https://wormholescan.io/#/tx/DXaLibokaRKbYfFdbnQGSj8XRMVVoiujHsMqxdfkiMa5)
* 0.0001 WAVAX transfer from Polygon (MetaMask) to Avalanche (MetaMask), link to [Wormholescan](https://wormholescan.io/#/tx/0x1d8d48f86562a0373a6a3bd59244006b47338393551b10d218fe37a71580cbb6)

**Comment by Wesleyleung** [comment] 2024-10-04 02:46
Seems like the issue is then that for CCTPRoute, transactions show up in the widget, but they do not have a timer and they still show even if the transaction has been completed.

**Comment by Wesleyleung** [comment] 2024-10-09 05:15
@emreboga any thoughts on why for CCTPRoute they are still showing here, but don't have a timer? I had thought the missing API from Wormholescan meant these type of txns don't show at all, but this case seems to contradict that.

**Comment by agodlevska** [comment] 2024-10-29 15:43
Checked on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGB2CmAuDuB7ATgawFxgOQFsCGAlpDLFgDThgCuBmwEAzgBaLwCSkACsogObLQGDAOoEAJrziZYyKtDABfChB5VYgzAG1KEAHT6AIgFEAYgEEAqgBkAKgH0ASgHkLNowGUyYHWACyeAE88SAdENWgyfyCQsPVfAGEbTi8o4NDw92E2ExtlCDB9XUhYWHT1BgAKUHz82ERUaEgGOh8a8wA5GydfOwt3A3itVpqwapHxgGMmQkhMLCNYJmgBKhxyYfH8SDxJZDmABgAPaAAhMXjoAE48S4BGAGYxS4AWff2jIwB2AFZoADN7rcLgAOABGYnuz2eADYAEwGfa3PC3Ca3dbjcZ1BqzbBHMz7UHA6GXO4TOG3MH3aGosS3S4GZ54WFXIyg%2FYTIxU%2FbQ07PYHojE1GTBBgTaAEABuyyGgvGY1lIzwYjEAiEB0O32%2Bf0%2BwNh%2B3u30%2B5lunzMtyM8VBfKMl2%2B9O%2BRmh90%2BoJMJlt0LE0JMAoVQoCAAdoHMkMgcCwADbQX1%2BpQbEYAXTygrjCvlsqmMzmJmCdTWydlWx20txh2hwLEJ1hf323zMTLEn0%2Bxj%2Bl2Btz%2BYlhoOg91h0OhD1eE0usLHJhOMcFWMa6thJk%2B93u%2B1tJ2B%2B3xz1B9zB%2BwMt3Z8WBwOe31hjMeK8JVLwU4xwqaYslJe0fvy6bfSpVgmapbBz0%2BGtmU%2BaA9RNZ4Jk%2BaE8FbA8lQmfYlWBPAt31Z5qwgu8FVgQNg2wUNw0QKMsIxVM%2FSTeMIDI8YKMFKxxEQOx4AYWAjBsAAJGVZQ%2FDFMyIOYFiWFZ80o%2FIi12dVQReZDLh3WFPi9ZDdRMaFvgeMxaR1S5oWeAwUOBQDQJOAxLhIoV6lnUtAPuS54m%2BdsTDtb4Tm%2Be4Jm%2BCZQTpUEEW3P4KzMalZIdWF4jwfYzNqZARSfKU9jAV831GUTxi%2FVVfywPFbjMeJ4luaAeTEPAqwc6BwTuTk1O%2BFd7hMW5jAc2EPIigs3xwoMQxQQjiNa2VqNlWi%2Bt6moeMmaZ%2BOwE5RUiiBxJLTKyzbW5HPJYkgROP5OQMMQDDPZ4xC%2BA8oNBT5LhMDd9nk%2FlhpGGccQW%2Ft3OgRE9q7R1YXXMw%2BRMWF3P2P4VIMaAQLPG1ByBGawAfUVxTiri31G2U0p%2FSTewXZ7y0%2BWEjH2MQVPiAwjRMA0Tk%2BPAUJOLyoWhAYSSJSH%2FQ6%2FCusjaMbvGfrBUGlMbu5kZhHhjFEZqPj7vcIjglvdmxMliTsE6WB60QAwACkmAadjoDwAA1Cx2MgAImHgUFOHaMx2mhYReBOAN2NQdiThsMlGwlKwAGlIbuuZgW%2BbWThMABFAAteJLhsIPUD%2BPAA1gE5hAAKwlCx4E%2BABNUEg%2FjgIz0CnB49gTgAHF45YgOzBwAPPeix9YZfFL33rmpkbVeWbEVvBlbVjWtd1%2FXDeN03zct63bftx3nc%2BV2PelzFcM6sNWYZxQZ7APnBQARyoRB1HirB2nXr0AA117MYErFBBh4ioQvgV8KxhGEKhOCJb52m16F44cW5fFBQ%2FoDdw4DJ2Lu1VpFTmIxhb5FFgJRYyxoCrEhnNXeRwEJYxONlIwAIqTQG2tAO0m5tIkkwc8aAwIcz2heF9a69cvalhOP9HM643jHh5IaEwRJlRnh0lJey3ZYQaQMqCbsdwq4xVrvFRKCNG75GbhlI4BhQSameKORsdI9y3FBHgIwwIcqghxjZW4QJnici%2BOhTG7Il4QHanhLABFF4ryoivNeIxwEjXrtA7AZhkCggIDIBBK8kHqlckuMQG4JiBUZKeDcypvTQAXDTGmDwfgLn7PEE4fJniewsvdI49CAZ4CYfsFheCjQcLEFwrctpdRCIES6YRaIV7Q1inXJKyVWkQFkeqfcBSzAnGJM9S6A5SGkzuMiZy8QAJqWeLcVyZhqqnjwNCSxUM57MwXkRNm0jXGJmltsiAkCIAeKwE4GOBAcAEAYCJN8gTSxImeHVPAp1%2Fqwlqn8KSTZYTaWpH04mnp4hensvqe40AHhZOxOqPJjC3hFKJCU9hnpyn9kqbwmpYhBH1NETXZ8EjpEHMVMqdK6pLg%2BTBC6M8nx4hfQKouYEExjLFTxmpeIY4YTQh%2BNCfYi4xDLOsfPbqmzWl7PyM4moQq8VHJOHgBgAq%2FQ3IWsEy8Zhwk6RQtVDSXoTBxKggYRJzpvgpOhGkjJYLLILUhQU6FxS2FlIqTw6p%2FC0V1Kkg0mh1cYbYsFmmaRHSCUo1LN0nRfTLgDP7DyYEIykQzJOBMn4txpmzPmd8RZPLVm2JZhspeQqIAivyNs5x%2FUFAAEo8gUUoFQaVDhoBiEEAQXgOI%2FERBAJQO6l9ECQD%2BLWloNRmKsQ4hfCYXaRgNACCGFibF2L9rvAwAIOBQREVHb29id5tiwGfPEca90poTDvHdNgYhB1jSzJNaaN1Omlker8F6543pwk%2Bt9X61UAY02Bng7G2lDHxDvOAggEw21zCYCUAMzQAD0wGpXStgAwXQv6iCSAmKgRA0HEA4GAzBpowGznFgYMBikwJITAZYsEIqyAxDAZ7eO3QAZIC8DvGhwu0B4OID3SGaKAYgxiAALQsTgEwWjREUBzAAMT3DMGYWqPperVomJhiMv4KQFn6sIBgEttgHvyMOuYSmVNS2GNO2d87sDCGXXgVdUp11HqwOLCMksd3ZOY203iG65hWZs6e31LcsA%2Bz9oHEOYcI5RxjnHROyc04ZyzjnaEecC7F1LuXSuvVv2%2FvugB2AQH0CgfA3AKDaG4MIaQyhtD2HMOSGwwaIpnwCOwCI3gEjZHkPIFZnYCMfBGJ%2FCoBGCMdhf3NeQHYZAvBQR2D1G8AMhw7BYzYwQOwbyoLQQmD7PAlHqMAH4TRFPLMCW0mTep0YYwh%2Bzab1k9WGFJmTv5oQKYLMIHjcDVhqYgBpwzN3hJTpnXOiMmnjOmegOZia8xYEvd6ru%2FdDnD1%2FcErdq5GIz1moYRa5hsLrUIttVUvhtShHOq%2Fb1H9f7sApbSxloQWWkOwb24h39BXEBECK%2FgErwGysGUq9V2rSAcANY2U1lr032ude6ygPrA2hvQtG%2BN2Ek3psnQHHgebSalu8FW58dbx4tt8aIPRxjB27EZskwxs7mB5M%2BEUzVnxficD3bAI9rAwhje%2BNkFDmoen3ufd6iutdTnPHeNt%2F44YwPzeHPd1gLxJu7ckRh7kuHhSrWlOR0iu1aPHUY5EQl7HSX%2F2AZA2BonkGSfUbJ%2Fl1DVP0PFcEPT6qjPCOQGI6R1n7Ooyc94K1nnXX%2BO9f64N4b%2BwRcTYDFNmbUuZeLao%2FLtbRJlffG28MXbGuQeHf5XeU7%2BBZP6%2BBJdnwwhECnPOZc83lv1%2Bb4ufb%2FIjuDNW6%2B27izJzV1b8P1YuzIPEZHMv2cg%2Fof3NyMOOayPiPo%2BcNj6j1F6KmOyewwOOyW6e6WmeEG2WheuW5OyGBe1OGGtOJeDOFWFeVedWbOjWzWDe3OHWzePWAu7ewuY23evekuc2C2cuCuSum24%2BqukA6u%2B2M%2BWux24wC%2BeAS%2BYABuoqV2mi0qO%2B0AI6hm%2FBMqDub2J%2BRmLuJm5%2Bf2kq0qtm2I9mD%2BAe8hYh%2BK34Hm4e%2BSX%2BrCP%2BiK3C%2F%2BDqgBSewwiWuOWA%2BOGemW2eOWeeFOCBReyBpWZeaBVWleNW1e9W2BXObW%2BBfOreguHeXeYuPeEus20uVBQ%2BNBo%2BdBE%2BkwheTBTGLB6abBIwHBXBPBuaeQcYCgAA3CAEAA).
Issue is no longer reproducible, the completed transaction is not displayed in the widget.
Transactions via CCTPRoute:
- [Wormholescan](https://wormholescan.io/#/tx/0x6615f3c34728981ede792807471b404d6f4c66b2010f08dd24d17aa1ee32cfe4)
- [Wormholescan](https://wormholescan.io/#/tx/0x7b1c1f11af63713f71f4e0d43db4aeea292bef2f687c2b31cd1f963beef45706)

Closing the ticket.

Attachment:
<img width="615" alt="Screenshot 2024-10-29 at 17 43 26" src="https://github.com/user-attachments/assets/b0ff9315-e388-4a17-9966-0ffe524f4a8d">

**Closed as completed by agodlevska** 2024-10-29 15:43 UTC
Labels: p2, connect v2
