### ISSUE TITLE
[QA][Mainnet] When changing wallet instead of selected wallet, Coin98 wallet extension is opened

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1575] opened 2024-01-30 09:31 UTC
Preconditions:
Leap wallet connected
Coin98 wallet extension enabled

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.234

Tested from: https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/#

Steps:
1. Click on connected Leap wallet to open drop down list
2. Select Change wallet
3. Click Keplr
4. Observe

Actual result: Instead of Keplr wallet extension, Coin98 is opened and offered to be connected to

Expected result: Keplr wallet extension is opened

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1a6780db-4719-460a-926d-0ec3de5b8630

**Comment by AigaD** [comment] 2024-02-08 09:26
Tested from: https://wormhole-connect.netlify.app/#
If Coin98 wallet is also present fro the Browser, then instead of Keplr wallet, Coin98 is opened when connecting to Sei Network

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e9dca47c-1b6b-479e-8818-831bc4c45b68

**Comment by tsadovska** [comment] 2024-10-10 14:52
Sei and Cosmos networks are currently not displayed in Networks list. Cannot reproduce the issue with different wallets and networks. 
Closing the ticket.

**Closed as not planned by tsadovska** 2024-10-10 14:52 UTC
Labels: p2
