### ISSUE TITLE
[QA] WETH instead of WGLMR asset is shown as received in the wallet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#829] opened 2023-08-17 08:24 UTC
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170
Tested from: https://base-relayer--wormhole-connect.netlify.app/# 
https://wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.02 GLMR from Moonbase to Fuji
2. Click Approve and proceed with transaction
3. When transaction is complete open transaction scan link to the receiving Network
4. Observe the received asset

Actual result: WETH asset is shown as received by the Network instead of WGLMR

Expected result: User receives WGLMR asset

Attachment:
TX 0.02 GLMR Moonbase -> Fantom
https://testnet.ftmscan.com/tx/0xb378153945a6208622a2c40e791e3bfc1641c32ba295510dbd77f2b8d4d744e0

<img width="1331" alt="Screenshot 2023-08-17 at 10 48 45" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/82d17442-4462-4d1d-a585-98a90449c439">

TX 0.02 GLMR Moonbase -> Fuji 
https://testnet.snowtrace.io/token/0xf080782df38ed5228d2fc2882d13d56c8f1d6f21
<img width="1325" alt="Screenshot 2023-08-17 at 10 27 20" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6fa935f8-5dc6-400c-b472-ece102fef286">

TX 0.01 GLMR Moonbase -> Fuji
https://testnet.snowtrace.io/tx/0x0a4d002825fe0b3d249dad93f55637d3104b4797fedd357e7d05128eebb01b7d

**Comment by AigaD** [comment] 2023-09-12 10:44
Reproduced also from: https://feature-configurable-routes--wormhole-connect.netlify.app/#
Transaction 0.02 GLMR from Moonbase to Fuji. In https://testnet.snowtrace.io/tx/0x18b993e667bd37bdf4509c27020acf2afdbb26b9469ba32e305e3daa9e5aa87c shows the received asset as 0.02 WETH instead of 0.02 WGLMR

Attachment:

<img width="1180" alt="Screenshot 2023-09-12 at 13 42 21" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a6cd12a5-49f9-4ce9-8cf4-7d95a909d08c">

<img width="1176" alt="Screenshot 2023-09-12 at 13 42 14" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f96d3aab-ad09-449f-98ba-441616b1affe">

**Comment by derpy-duck** [comment] 2023-09-13 21:49
This turns out to be an issue with how this token shows up on testnet snowtrace - the token received is indeed the wrapped GLMR token (should be called 'DEV') - but it is just labelled as 'WETH' on the interface !

**Comment by tsadovska** [comment] 2023-09-14 20:14
Issue is not reproducible on https://latest--wormhole-connect.netlify.app/ [Mainnet]. WGLMR asset is shown correctly in Snowtrace.

- Send from tx: [Moonscan](https://moonscan.io/tx/0x538c91c77785b8946b5b863591cc8d4f7a1be6ff58f0415b40c0597b04139505)
- Send to tx: [Snowtrace](https://snowtrace.io/tx/0xf139cb2a4f205920064153f47acfc4d703ab9fcb513f73c759c5821c60bff4db)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a8a6f028-337f-4976-a191-a704a99fb819)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/28d64ea0-16a8-41be-8747-fd0d1606127d)

**Comment by AigaD** [comment] 2023-09-25 11:06
Issue is reproducible from: https://deploy-preview-1015--wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7ec5c5ba-7aa6-48df-ba5f-e7a07e12db4d

**Comment by anondev2323** [comment] 2023-10-06 18:26
The token in testnet is actually labelled WETH.  It is an issue with the explorer and not Connect.  So I'm going to close this.  For reference, this is actually WGLMR: https://moonbase.moonscan.io/address/0xd909178cc99d318e4d46e7e66a972955859670e1

**Closed as completed by anondev2323** 2023-10-06 18:26 UTC
Labels: p1
