### ISSUE TITLE
[QA] Message to register token and No bridge or swap route available are both shown at the same time

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2081] opened 2024-05-15 06:02 UTC
Precondition:
none

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
[Testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDACIAjAJwEsATAc0gBFIAzAQwFcAbFdIxUCCEzIB7ALYA5HAHdhZANaIk%2BQhBTDJKGfMXKBYNXJg6CEAL4hTQA%3D#)

> {
  env: 'testnet',
  "bridgeDefaults": {
    fromNetwork: '',
    toNetwork: '',
    token: '',
  }
}

Steps:
1. Select Sepolia network at sending From section
2. Connect Metamask wallet
3. Select Solana network at sending To section
4. Connect Solflare wallet
6. Select WMATIC asset
7. Enter some amount e.g. 0.02 WMATIC
8. Change WMATIC asset to ETH (Sepolia)
9. Observe

Actual result: Both messages "This token is not registered, you must [register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register) it before you continue. Newly registered tokens will not have liquid markets." and "No bridge or swap route available for selected tokens" are shown

Expected result: Message "No bridge or swap route available for selected tokens" is shown without token registration message

Attachment:

<img width="712" alt="Screenshot 2024-05-15 at 08 55 05" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/dfc23b59-a4b8-4551-852a-9ca1cfa67ba5">

**Comment by agodlevska** [comment] 2024-09-24 08:01
The issue is no longer relevant after the redesign, it is impossible to select the WMATIC token in the scenario described above.
Closing the ticket.

Attachment:
<img width="1440" alt="Screenshot 2024-09-24 at 10 59 26" src="https://github.com/user-attachments/assets/746ec693-b625-4873-8808-c58bb09c8223">

**Closed as not planned** 2024-09-24 08:11 UTC
Labels: p2
