### ISSUE TITLE
[QA] [Testnet] Leap wallet notification appears again after user closes it

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2104] opened 2024-05-20 15:51 UTC
## Describe the current behavior in detail
Checked on [testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDACIAjAJwEsATAc0gBFIAzAQwFcAbFdIxUCCEzIB7ALYA5HAHdhZANaIkw9KOUV0%2BQhBTDJKGfMWaBYHXJhGCEAL4hrQA%3D%3D) with macOS Sonoma 14.4.1 and Google Chrome Version 125.0.6422.61 (Official Build) (arm64).

Steps:
1. Select Osmosis network as source chain
2. Click Close button in Leap wallet notification
3. Check if wallet notification appears again

Actual result: Leap wallet notification appears again after user closes it.
Expected result: Leap wallet notification no longer appears.

## Notes/ Attachments
Issue is not reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://portalbridge.com/ [Mainnet].

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f4c63fda-c69b-4af7-9c85-bb11337298c7

**Comment by agodlevska** [comment] 2024-10-03 12:31
The issue is no longer relevant after the redesign, Cosmos chains are not available on https://wormhole-connect.netlify.app/.
Closing the ticket.

**Closed as not planned by agodlevska** 2024-10-03 12:31 UTC
Labels: p2
