### ISSUE TITLE
[QA] [Mainnet] BaseScan link leads to invalid transaction hash result

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2057] opened 2024-05-08 11:42 UTC
## Describe the current behavior in detail
Checked on https://preview.portalbridge.com/bceadc8c64/ [Mainnet] with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.119 (Official Build) (arm64). 

Steps:
1. Send 0.0004 wstETH (Polygon) from Polygon (MetaMask) to Base (MetaMask) or resume transaction 0x6155f4bf7a55bb4a8159ab54f967760208d7edf57c3135c64e37769fc0990ba6 (Polygon)
2. Click on BaseScan link

Actual result: Page is opened https://basescan.org/tx/62b412a6dc1f310a1f63765723b5241f0ff794ebff4b1dddde4a913affc63b64. Error "Oops! An invalid Txn hash has been entered: 62b412a6dc1f310a1f63765723b5241f0ff794ebff4b1dddde4a913affc63b64". 

Expected result: Correct link is https://basescan.org/tx/0x62b412a6dc1f310a1f63765723b5241f0ff794ebff4b1dddde4a913affc63b64 

## Notes/ Attachments
Similar issues: #1919, #1909.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e508b8b9-5d0a-4ab2-8e3c-60ae24c9e2a8)

**Comment by tsadovska** [comment] 2024-05-30 09:41
Reproducible on https://deploy-preview-2143--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0014 WETH (Polygon) -> WETH (Base) through ETH Bridge route from Polygon (MetaMask) to Base (MetaMask). 
* Send from tx: [Polygonscan](https://polygonscan.com/tx/0x49efa1e5ceaac60a2bab04efd3bca2a064e0d8ec5ec551c2b379799a888cf847)
* Send to tx: [BaseScan](https://basescan.org/tx/7522000d7f10e1248212b49035d371f0cd4b13cd3729191e0b89bd12d71d0573) instead of [BaseScan](https://basescan.org/tx/0x7522000d7f10e1248212b49035d371f0cd4b13cd3729191e0b89bd12d71d0573)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x49efa1e5ceaac60a2bab04efd3bca2a064e0d8ec5ec551c2b379799a888cf847)

**Comment by agodlevska** [comment] 2024-06-26 07:27
Reproducible on https://preview.portalbridge.com/8b6491733c/ [Mainnet] when sending 0.0001 WETH (Arbitrum) → WETH (Base) through ETH Bridge route from Arbitrum (MetaMask) to Base (MetaMask).

- Send from tx: [Arbitrum](https://arbiscan.io/tx/0x0f9db1194eebae0e07cec0d93a3e7d0f74d24a06ef22b3eabd96f765799811ba)
- Send to tx: [BaseScan](https://basescan.org/tx/6c7dea59a8faa977bffe8696dd39bfa5d22098a50890a7c4f06992553b447ff3) instead of [BaseScan](https://basescan.org/tx/0x6c7dea59a8faa977bffe8696dd39bfa5d22098a50890a7c4f06992553b447ff3)
- Link to [Wormholescan](https://wormholescan.io/#/tx/0x0f9db1194eebae0e07cec0d93a3e7d0f74d24a06ef22b3eabd96f765799811ba)

**Comment by tsadovska** [comment] 2024-07-11 10:05
Reproducible on https://preview.portalbridge.com/3365c86aff/ [Mainnet] when sending 0.943075 USDT from Polygon (MetaMask) to Base (MetaMask) with USDT route. 
* Send from tx: [Polygonscan](https://polygonscan.com/tx/0xe602014817ffe8e63298ff4a6fc2619cea64c36b0dff9b5fae5fa6071fd0878d)
* Send to tx: [BaseScan](https://basescan.org/tx/f25f89e6bad04cae16972fcb2050b2a047292b83a0f250f3191ece1916f5892a) instead of [BaseScan](https://basescan.org/tx/0xf25f89e6bad04cae16972fcb2050b2a047292b83a0f250f3191ece1916f5892a)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0xe602014817ffe8e63298ff4a6fc2619cea64c36b0dff9b5fae5fa6071fd0878d)

**Comment by agodlevska** [comment] 2024-08-27 07:14
Reproducible on https://preview.portalbridge.com/b3b7091778/ [Mainnet] when sending 0.1 USDT from Optimism (MetaMask) to Base (MetaMask) with USDT route.

- Send from tx: [Optimism](https://optimistic.etherscan.io/tx/0xf083ea17c472e196b4176de6504311da434c166f4bf9deeeb10c7f76fc730cbe)
- Send to tx: [Base](https://basescan.org/tx/5387c0b0929a0545925d0a8b4dcf4ae773da64549106257c2fb31fda3654e417) instead of [Base](https://basescan.org/tx/0x5387c0b0929a0545925d0a8b4dcf4ae773da64549106257c2fb31fda3654e417)
- Link to [Wormholescan](https://wormholescan.io/#/tx/0xf083ea17c472e196b4176de6504311da434c166f4bf9deeeb10c7f76fc730cbe)

**Comment by agodlevska** [comment] 2024-09-24 07:55
The issue is no longer relevant after the redesign, link on destination chain is no longer displayed. 
Closing the ticket.

**Closed as not planned by agodlevska** 2024-09-24 07:55 UTC
Labels: p2, explorer
