### ISSUE TITLE
[QA] Error "Failed to load wallets" occurs when user changes account in extension  

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1912] opened 2024-04-10 16:56 UTC
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Prepare to send 0.025 WAVAX from Avalanche (MetaMask) to Celo (MetaMask) with automatic route
2. Enable "Native gas" section and change slider position
3. Click "Approve and proceed with transaction" button
4. Wait for the transaction to complete
5. Open MetaMask extension and change account
6. Click on "Add WAVAX to your account" link on wormhole-connect
7. Check if wallets are loaded

Actual result: Error "Failed to load wallets" occurs. 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0ff5f8fe-d0e8-4819-9bde-275a92c4861e

## What is the expected/desired behavior
Wallets are loaded.

**Comment by agodlevska** [comment] 2024-10-07 08:43
The issue is no longer relevant after the redesign, after the transaction is completed there is no more option to add the token to the wallet. 
Closing the ticket.

**Closed as not planned by agodlevska** 2024-10-07 08:43 UTC
Labels: p2
