### ISSUE TITLE
[QA]Missing Fee and sent asset info when TX is completed

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#975] opened 2023-09-14 06:02 UTC
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://cctp-only--wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.0001 USDC from Avalanche to Arbitrum Goerli
2. Click Approve and proceed with transaction
3. Click Claim when possible
4. Observe Sent From and Sent To fields

Actual result: Sent From field is missing info regarding paid fees, sent asset value

Expected result: Fee information and sent asset is shown at Sent From section

Attachment:
https://snowtrace.io/tx/0x8f6e5a7bd28074e3ca60508b6942bb86db0d344fc644ee736b8588c848cd10f5

<img width="1255" alt="Screenshot 2023-09-14 at 08 56 47" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9495f293-2d54-4c9e-8ddb-2bcd816fd332">

<img width="1233" alt="Screenshot 2023-09-14 at 15 33 39" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/01a7da1a-a8ed-4245-950f-c049c57746b2">

**Comment by tsadovska** [comment] 2023-09-14 15:07
Please see #966 for more scenarios.

**Comment by tsadovska** [comment] 2023-09-14 15:14
Issue is reproducible on https://cctp-only--wormhole-connect.netlify.app/ [Mainnet] when:
* sending 1.5 USDC from Avalanche (Metamask) to Arbitrum (Metamask). One transaction option was selected in Route section. Send from tx: [Snowtrace](https://snowtrace.io/tx/0x1c6dfd0dda2a80f17129241d13cc0307ad6d3609aedaeb39eff091a80f02333a)


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/bd9c2da1-ae1e-452a-b411-30a39a3bfea0)

* sending 3 USDC from Avalanche (Metamask) to Arbitrum (Metamask). One transaction option was selected in Route section. Send from tx: [Snowtrace](https://snowtrace.io/tx/0xc3d2559305dd7a8ce3a512f216d909e27c0dce16101bc01f968a248d301e5b5e)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b4d6080d-ddff-4323-a16a-29d981f37cce)

**Comment by tsadovska** [comment] 2023-09-20 15:39
Scenarios Tested OK on https://deploy-preview-1014--wormhole-connect.netlify.app/ [Testnet]:
* Send 0.01 USDC with "Two transactions" from Fuji (Metamask) to Arbitrum Goerli (Metamask)
* Send 0.3 USDC with "One transaction" from Fuji (Metamask) to Arbitrum Goerli (Metamask)
* Send 0.3 USDC with "One transaction" from Goerli (Metamask) to Fuji (Metamask) 

Scenarios Tested OK on https://deploy-preview-1005--wormhole-connect.netlify.app/ [Mainnet]:
* Send 1.5 USDC with "One transaction" from Avalanche (Metamask) to Arbitrum (Metamask)
* Send 3 USDC with "One transaction" from Avalanche (Metamask) to Optimism (Metamask)

**Comment by AigaD** [comment] 2023-12-14 16:37
Re-opening this ticket.
Tested NOK from: https://deploy-preview-1312--wormhole-connect-mainnet.netlify.app/
[Arbitrum explorer](https://arbiscan.io/tx/0xaae3eb0426dfd109fa1a08fae454d8c6cc8bca20878ddba453e4ba7032d06470)
Comments: Link to [Polygonscan](https://polygonscan.com/tx/0xf5b9997ee285e6405bd0c804c43f88605c978e0861c9886d050dfa28ae647ad9) was shown after finding the transaction in Resume transaction
Attachment:
![Screenshot 2023-12-14 at 18 34 40](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fa83019a-0233-4f18-bb05-05c308edaa93)

**Comment by tsadovska** [comment] 2023-12-14 18:34
"Send to" section is incomplete when sending 5 USDC from Avalanche (Metamask) to Polygon (Metamask). Checked on https://deploy-preview-1312--wormhole-connect-mainnet.netlify.app/ [Mainnet].

- Send from tx: [Avanscan](https://avascan.info/blockchain/c/tx/0x3a95fb88d0ad404cc3368eddf65622e15ec4ae372e6ec3751d08ca43c9b7d52e)
- Send to tx: [Polygonscan](https://polygonscan.com/tx/0x3d130c286a3609ae4f6e7bf9c96ab2976786b0cf5e5737228ebac9985858df0d)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/903556e7-0714-44df-9949-ea345f6196e9)

**Comment by tsadovska** [comment] 2024-01-11 08:31
Issue is reproducible on https://preview.portalbridge.com/bf7b5b43a8/ [Mainnet] when resuming tx.
Tx hash: 0x4ba10e5a7a9f7baa345a8876b920c4ba9b5057bce22f6da546498c6d1ca4d81f (Ethereum). 

<img width="553" alt="Screenshot 2024-01-11 at 10 28 31" src="https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/23ad9b38-93da-4752-a16b-a34278876f74">

**Comment by AigaD** [comment] 2024-01-11 09:12
Tested from: https://preview.portalbridge.com/bf7b5b43a8/# and https://wormhole-connect-mainnet.netlify.app/#
For transaction 0.001 ETH from Ethereum to BSC when transaction was completed Send to section did not have any transaction information.

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/32793519-d10b-4924-ac62-1730c885cf9a

Transaction wstETH from [Ethereum](https://etherscan.io/tx/0x10a3e983b70d4e2b162d36f60a3abed3acdb14e3d9ec4f70d2443de7d8881416) to Polygon did not have any information at sending From and sending To section regarding amount and fees

Attachment:

![Screenshot 2024-01-11 at 12 45 30](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4afe9025-996b-4f60-b8aa-ab27d5cae73d)

![Screenshot 2024-01-11 at 13 22 08](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/aeaeed82-4f20-44a0-be7d-f5987d9b11fb)

**Comment by tsadovska** [comment] 2024-01-11 15:26
Issue is also reproducible when sending wstETH from Arbitrum to Polygon.
Checked on https://preview.portalbridge.com/bf7b5b43a8/ [Mainnet].

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9b663f2c-687e-479a-90b0-a809228d30b8


![Screenshot 2024-01-11 at 17 53 04](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/aa03de88-3275-47bc-a3ef-db7ca0927f32)

**Comment by kev1n-peters** [comment] 2024-01-11 16:46
The send from section should be fixed in this PR https://github.com/wormhole-foundation/wormhole-connect/pull/1457 (for the ETH Bridge and wstETH Bridge routes) and the Send to section isn't showing, because WormholeScan doesn't have the destinationTx in the call to global-tx. The redeem TX is too old to be "efficiently" queried from the RPC without walking blocks backwards

**Comment by AigaD** [comment] 2024-01-12 15:45
Re-opening the ticket, because we have encountered multiple transactions where some info is missing.
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Attachment:
TX from [Polygon](https://polygonscan.com/tx/0x2ab07cd0844330077944c5c6c844bd01ec8ee912283f62047627db06c21ec981) to Arbitrum

<img width="609" alt="Screenshot 2024-01-12 at 17 23 46" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1a352bf1-6deb-480c-bb50-8182efaf6fec">

TX from [Base](https://basescan.org/tx/0xe071b3577426cd753226a3d2f7d91f97fa7938a2cf73d8f9cf706b0e87e46ac4) to Ethereum

Comments: It seems that when the TX is finished the transaction details are not shown, bet when resumed they are present.

**Comment by kev1n-peters** [comment] 2024-01-13 16:15
> Re-opening the ticket, because we have encountered multiple transactions where some info is missing. Tested from: https://wormhole-connect-mainnet.netlify.app/# Attachment: TX from [Polygon](https://polygonscan.com/tx/0x2ab07cd0844330077944c5c6c844bd01ec8ee912283f62047627db06c21ec981) to Arbitrum
> 
> <img alt="Screenshot 2024-01-12 at 17 23 46" width="609" src="https://private-user-images.githubusercontent.com/91047061/296283757-1a352bf1-6deb-480c-bb50-8182efaf6fec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxNjI0MzUsIm5iZiI6MTcwNTE2MjEzNSwicGF0aCI6Ii85MTA0NzA2MS8yOTYyODM3NTctMWEzNTJiZjEtNmRlYi00ODBjLWJiNTAtODE4MmVmYWY2ZmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDE2MDg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZDg3MDQ2ODIwZmY5NzU3NzhmNTNiODQzYzQwZWI4MWE1YWZiNjQ1MzdiYjBkOGQ1MGJlYTNjNjJkNDk0NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e6HAOrfPRutooO4usfudU89GqS1LRst1a5A0FOJH3JA">
> TX from [Base](https://basescan.org/tx/0xe071b3577426cd753226a3d2f7d91f97fa7938a2cf73d8f9cf706b0e87e46ac4) to Ethereum
> 
> Comments: It seems that when the TX is finished the transaction details are not shown, bet when resumed they are present.

This should be the opposite. The TX details may not  always be present when resuming (depending on how old the TX is), but they should always be present when the TX is finished using the normal transfer flow. Can you confirm this?

**Comment by tsadovska** [comment] 2024-01-15 10:45
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0019 wstETH (Optimism) from Optimism (Metamask) to Ethereum (Metamask) using the normal transfer flow. "Send to" section is incomplete. Tx timestamps: Jan-15-2024 10:07:39 AM +UTC. 
* Send from tx: [Optimism](https://optimistic.etherscan.io/tx/0x903af596bdfa711f33d79b5229588a10416552ac73004f9db85d649bb1e13aa8)
* Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/0x903af596bdfa711f33d79b5229588a10416552ac73004f9db85d649bb1e13aa8)


![Screenshot 2024-01-15 at 12 41 36](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/09aed583-287b-493a-8b7e-45a0e2b0a0bd)

**Comment by tsadovska** [comment] 2024-01-16 08:30
Issue is also reproducible on https://deploy-preview-1476--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0007 ETH from Ethereum (Metamask) to Avalanche (Metamask) using the normal transfer flow. "Send to" section is incomplete. 
* Send from tx: [Etherscan](https://etherscan.io/tx/0x84122afe197b00f0a4b96439faac7b9ff6b058cfbec7fb125f420c0353e9dd9b)
* Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/0x84122afe197b00f0a4b96439faac7b9ff6b058cfbec7fb125f420c0353e9dd9b)


![Screenshot 2024-01-16 at 10 36 54](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b73fab9d-831a-48f9-bb60-960eb03ea020)

**Comment by AigaD** [comment] 2024-01-24 11:59
Reproduced from: https://preview.portal-bridge-ui.pages.dev/c0216a7edf/
Fee info and received asset is missing at target chain when transaction is completed.
Attachment:

<img width="989" alt="Screenshot 2024-01-24 at 13 58 54" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8b94443c-b280-44c4-8a37-731b27e6360e">

**Comment by AigaD** [comment] 2024-02-01 10:25
Reproduced from: https://deploy-preview-1543--wormhole-connect-mainnet.netlify.app/#
Attachment:

![Screenshot 2024-02-01 at 12 23 53](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f4044dd4-ce8d-4171-b70e-09076f492f49)

**Comment by tsadovska** [comment] 2024-02-26 08:52
Issue is reproducible on https://preview.portalbridge.com/7246284e5d/ [Mainnet] when sending 1 BONK from Solana (Phantom) to BSC (MetaMask). "Amount" and "Gas fee" fields are not displayed in "Send to" section on Redeem screen. 
* Send from tx: [Solana Explorer](https://explorer.solana.com/tx/2MiSkDjXwXaVBVFSANMqYSRLx4KNBPkTNXEGDoDLhHVyZpzA23UFECfPPWHZZexVLP3YDKEXMjQc7D5AJYbgY2hG)
* Send to tx: [BscScan](https://bscscan.com/tx/0xa8e53be5c7eedefe9a2e4aeb51c3b1a619a907c3cb4e2588f2943f6ebd208822)


Reproducibility: Reproduced only once. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2aec0525-95ac-4063-91dd-536371fb8366)

**Comment by tsadovska** [comment] 2024-03-07 09:16
Issue is reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending 0.001 wKLAY from Fantom (MetaMask) to Sui (Sui wallet). Reproducibility: 1/10. 

* Send from tx: [FtmScan](https://testnet.ftmscan.com/tx/0x1ac5ec9e575dfd940b475188adc54754cc9168fb7178efe8ea630fc9c2af51d3)
* Send to tx: [Sui explorer](https://suiexplorer.com/txblock/9X4Npcq1fgndBKyPPWxT1R6HDGbSeJyuSJ5Tw6kMqKZ3?network=testnet)

Error:
```
Error: RPC Error: Could not find the referenced transaction [TransactionDigest(9X4Npcq1fgndBKyPPWxT1R6HDGbSeJyuSJ5Tw6kMqKZ3)].
    at JsonRpcClient$1.requestWithType (main.js:292:944)
    at async JsonRpcProvider.getTransactionBlock (main.js:292:33909)
    at async SuiContext.getTxGasFee (main.js:319:202095)
    at async WormholeContext.getTxGasFee (main.js:322:627001)
    at async BridgeRoute.getTransferDestInfo (main.js:324:15550)
    at async main.js:500:111
```


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/c045346e-9288-4d10-bdd8-eb9429aa5dfa)

**Comment by AigaD** [comment] 2024-03-11 11:18
Reproduced from: https://wormhole-connect-mainnet.netlify.app/#
Fee and sent asset information missing for transaction 0.01 wstETH from Arbitrum to Optimism
Attachment:

![Screenshot 2024-03-11 at 13 15 32](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/803d7c90-0f21-476d-9f1b-b3e9f5ade417)

**Comment by tsadovska** [comment] 2024-03-15 14:45
Issue is reproducible on https://deploy-preview-1795--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.002 PYTH from Solana (Phantom) to Avalanche (MetaMask). 
* Send from tx: [Solana Explorer](https://explorer.solana.com/tx/QJUA3EhKppx6a2jY25UJ6sKQmxWiRSBaa1A7o3D4yw871V2cPmgmBBw2z6UFb8hxCW68CprR4ychsLktQHgCGGT)
* Send to tx: [Avascan](https://avascan.info/blockchain/c/tx/0x3dd8aff6c53dfada23022ba617c32eeb8148fc76a5ad0e42679acaecda45c895)


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/36112a8c-5913-4625-83e6-468b73016879)

**Comment by tsadovska** [comment] 2024-03-21 17:02
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0001 SUI from Evmos (Leap) to Sui (Sui wallet). 
* Send from tx: [Mintscan](https://www.mintscan.io/evmos/tx/5B25CE6A2C89675EF684A55003B7C825549F730691CD97795429F5658DC2B4DF)
* Send to tx: [Sui explorer](https://suiexplorer.com/txblock/7TvUYr26KnLSS8ZckTi1L3ottCFb7ogPsZ9gaHwcdJAW)
* Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/3104/aeb534c45c3049d380b9d9b966f9895f53abd4301bfaff407fa09dea8ae7a924/28381)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2d77f12b-1d78-462e-b774-31aed94f395c)

**Comment by AigaD** [comment] 2024-04-10 07:47
Reproduced from: https://portalbridge.com/#
For transaction WETH from [Polygon](https://polygonscan.com/tx/0xf80c7a36fc325ab078e0f0d4f0cc1f9db984be9286a5846c3cfe8509f790cb04) to BSC, missing information in Sent To section
Attachment:
<img width="1040" alt="Screenshot 2024-04-10 at 10 45 36" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e6230125-647e-4280-a1db-0336b9bf81a6">

**Comment by AigaD** [comment] 2024-05-02 09:11
Tested from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJIWIRcIybhnzFywWDVyYOohAC%2BIU0A%3D#)
Missing gas fee information for Sui, when transaction 0.001 USDC from Evmos (Leap) to Sui (Sui) is completed.
Attachment:

<img width="1025" alt="Screenshot 2024-05-02 at 12 09 35" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e292580a-903d-4101-b316-3ad98ebffba2">
<img width="1120" alt="Screenshot 2024-05-02 at 12 09 29" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/58f671ba-1107-4ecb-a0b4-8f1cd28a8cee">

**Comment by tsadovska** [comment] 2024-05-07 12:33
Reproducible on https://preview.portalbridge.com/bceadc8c64/ [Mainnet] when sending 0.011 SUI from BSC (MetaMask) to Sui (Sui wallet). 
* Send from tx: [BscScan](https://bscscan.com/tx/0xfb360ec2fd3a804975b35aca283c9d99713bc2e1dec55933c633af1043e442cd)
* Send to tx: [Sui Explorer](https://suiscan.xyz/mainnet/tx/CdDEsjGt7s4nX3LgEAR3GiGJZKTdXNcpfcLEKdRCu6cp)
* Link to Wormholescan: [Wormholescan](https://wormholescan.io/#/tx/0xfb360ec2fd3a804975b35aca283c9d99713bc2e1dec55933c633af1043e442cd)


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/88d0163e-645d-4286-93e3-83cf3e83c68c)

**Comment by tsadovska** [comment] 2024-05-13 14:21
Reproducible on https://preview.portalbridge.com/3064c36d95/ [Mainnet] when sending 0.01 wKLAY from Blast (MetaMask) to Sui (Sui). 
* Send from tx: [Blastscan](https://blastscan.io/tx/0x87602a87c7e641815a69a1ce69142a75bf6ef154bdd7cb70b9ed3bc78cd2ee2c)
* Send to tx: [Sui Explorer](https://suiscan.xyz/tx/76JChSVQc5rjCbrGAEuGU2rT8o38AwRhbmXLWXkAmBD3)

```
Error: RPC Error: Could not find the referenced transaction [TransactionDigest(76JChSVQc5rjCbrGAEuGU2rT8o38AwRhbmXLWXkAmBD3)].
    at JsonRpcClient$1.requestWithType (pb-index-u9c9TQ3X.js:468:958)
    at async JsonRpcProvider.getTransactionBlock (pb-index-u9c9TQ3X.js:468:34107)
    at async SuiContext.getTxGasFee (pb-index-u9c9TQ3X.js:495:210787)
    at async WormholeContext.getTxGasFee (pb-index-u9c9TQ3X.js:498:607463)
    at async BridgeRoute.getTransferDestInfo (pb-index-u9c9TQ3X.js:502:69993)
    at async pb-index-u9c9TQ3X.js:728:111
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ac58196b-9223-4435-816f-f0a1575cbebe)

**Comment by AigaD** [comment] 2024-05-13 15:18
Reproduced from: https://preview.portalbridge.com/3064c36d95/#
Transaction 0.001 WMATIC from [Blast](https://blastscan.io/tx/0xb5024cbde1b0193fd54756e6bb1536ffb180c08091502f546bfc4c7ab03f1b59) to Base gas fee and amount information missing when transaction is completed.
Attachment:

<img width="1052" alt="Screenshot 2024-05-13 at 18 16 04" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1edd590e-a15d-4116-aa05-9d1387c7d736">

**Comment by AigaD** [comment] 2024-05-17 07:02
Reproduced from: https://deploy-preview-2080--wormhole-connect-mainnet.netlify.app/#
Missing BSC explorer link, sent asset info and gas fee information when transaction 0.0004 ETH from [Ethereum](https://etherscan.io/tx/0x8c53473b102fb1caa5316eb581fa889ee99cbc67fbca6d78c804b60dc2a34446) to BSC is completed
Attachment:

<img width="1075" alt="Screenshot 2024-05-17 at 10 01 02" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/fca8a22c-d420-4dc9-b78b-a5bfee22b4ec">

**Comment by AigaD** [comment] 2024-05-20 08:06
Tested from: https://deploy-preview-2080--wormhole-connect-mainnet.netlify.app/#
For transaction 0.00033 WETH from BSC to Optimism missing explorer link and sent asset info when transaction is completed
Attachment:

<img width="1080" alt="Screenshot 2024-05-20 at 11 05 05" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d80fcca2-de44-436b-9017-2fc8eefd82d8">

**Comment by agodlevska** [comment] 2024-05-23 07:47
Reproducible on https://deploy-preview-2113--wormhole-connect-mainnet.netlify.app/# when sending 0.001 SOL from Solana (Solflare) to Sui (Sui).

- Send from tx: [Solana](https://explorer.solana.com/tx/2N1gabxKsftP9r71sGJgRqHV1GmNb4dFHSeT8eYzUCA3ywocExywNTa6QN6yFMAobKD1nTofN2qGNfKRojDoswty)
- Send to tx: [Sui](https://suivision.xyz/txblock/4MSP6wPeUYB8hTEi9U7h4kX4bECm8enrjyn3DrneuF9B)

`Error: RPC Error: Could not find the referenced transaction`

Attachment: 
<img width="1440" alt="Screenshot 2024-05-23 at 10 43 44" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/85c1361d-1526-4149-b94d-71d2b55b6230">

**Comment by tsadovska** [comment] 2024-05-28 21:21
Reproducible on https://preview.portalbridge.com/3064c36d95/ [Mainnet] when sending 0.0012 WSOL from [X Layer](https://www.okx.com/web3/explorer/xlayer/tx/0x5334ed0213e6d3d7cd80de4193abce9abdfb79cdae641f56bcc60a6988ec40ee) (MetaMask) to [Sui explorer](https://suiscan.xyz/mainnet/tx/7s16kAEma7fiJFmLJsQVGUotCf7XSdBKhsoxTUzoqn3L) (Sui)

```
Error: RPC Error: Could not find the referenced transaction [TransactionDigest(7s16kAEma7fiJFmLJsQVGUotCf7XSdBKhsoxTUzoqn3L)].
    at JsonRpcClient$1.requestWithType (pb-index-DSi4RVd3.js:481:958)
    at async JsonRpcProvider.getTransactionBlock (pb-index-DSi4RVd3.js:481:34079)
    at async SuiContext.getTxGasFee (pb-index-DSi4RVd3.js:508:210968)
    at async WormholeContext.getTxGasFee (pb-index-DSi4RVd3.js:511:627532)
    at async BridgeRoute.getTransferDestInfo (pb-index-DSi4RVd3.js:516:84601)
    at async pb-index-DSi4RVd3.js:743:111Caused by: Error: Could not find the referenced transaction [TransactionDigest(7s16kAEma7fiJFmLJsQVGUotCf7XSdBKhsoxTUzoqn3L)].
    at JsonRpcClient$1.requestWithType (pb-index-DSi4RVd3.js:481:1023)
    at async JsonRpcProvider.getTransactionBlock (pb-index-DSi4RVd3.js:481:34079)
    at async SuiContext.getTxGasFee (pb-index-DSi4RVd3.js:508:210968)
    at async WormholeContext.getTxGasFee (pb-index-DSi4RVd3.js:511:627532)
    at async BridgeRoute.getTransferDestInfo (pb-index-DSi4RVd3.js:516:84601)
    at async pb-index-DSi4RVd3.js:743:111
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/13f87f46-3764-499d-8949-cb7d74c18515)

**Comment by tsadovska** [comment] 2024-06-14 15:26
Rechecked scenarios mentioned in the ticket.

1. Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]. Fees and asset info are displayed correctly in “Send from” and “Send to” sections when sending:

- USDC from [Avalanche](https://avascan.info/blockchain/c/tx/0x97389633266170c2668643e0a86f40b1a83d54133a5da86b715f47752a585272) (MetaMask) to [Arbitrum](https://arbiscan.io/tx/0xe5011d4075e8d62190f7f5ec3dddac4a4343fbe77b2d3079f72d52da4e99b6f1) (MetaMask) with Circle CCTP manual route
- USDC from [Avalanche](https://avascan.info/blockchain/c/tx/0x56ed53267905a0c3b1de58c0c03034f486d380e822ca8d521f95bdc5ee563fda) (MetaMask) to [Arbitrum](https://arbiscan.io/tx/0xa96e1150ee7cdf6a63f00f31da54d3c6a37b90c21e0c5fc40b8df69a0689441b) (MetaMask) with Circle CCTP automatic route
- USDC from [Avalanche](https://avascan.info/blockchain/c/tx/0xfea601ebf80709416e938e1e7fd6dd3b4a3862abce37d5844a6bfd6b43e92c66) (MetaMask) to [Optimism](https://optimistic.etherscan.io/tx/0x4733aac7dff1d91a6cb6220577e9b2ec29ac147a3b9fab9b046e91eef3312adc) (MetaMask) with Circle CCTP automatic route
- USDC from [Avalanche](https://avascan.info/blockchain/c/tx/0x5febc116431245f91a286b3ad9335b61bbd8418b6ca5068120c9b86aff87bd3a) (MetaMask) to [Polygon](https://polygonscan.com/tx/0x40c02e6e26afd9f966d11d242abeb98fd691ba6033d9fc62324703c7805a60ab) (MetaMask) with Circle CCTP automatic route
- ETH from [Ethereum](https://etherscan.io/tx/0x1838c63ae363824a261de857a29831874aa0e58c868943028dc0ff24d06c996f) (MetaMask) to [Arbitrum](https://arbiscan.io/tx/0x9f9d8cf437144f2af11f750e15ed46614f93f6075f48ba57a709df43501ae0f9) (MetaMask) with ETH Bridge route 
- ETH from [Ethereum](https://etherscan.io/tx/0x43f689e011791ced4b49a4c813bac3c7f5d93f3987cf35da652546fd5bcefe11) (MetaMask) to [BSC](https://bscscan.com/tx/0x5d56ea4bd7f6231f040ea409c7ab1ca0b34d5c3049d62ad5b1e5d31ef4d2aef0) (MetaMask) with ETH Bridge route
- ETH from [Ethereum](https://etherscan.io/tx/0x13fc53ea8f027a2271080984c707dc17520cda9f48b39224b1777a8f6d212e7b) (MetaMask) to [Avalanche](https://avascan.info/blockchain/c/tx/0xa9ee209badb589df2cb6ca6aac6a856664a9e3550cd43196a1830763212ccc0a) (MetaMask) with ETH Bridge route
- wstETH from [Ethereum](https://etherscan.io/tx/0x25341be40a64653268ba8383a12f84b2fcd7f99812e27c69456fab7db3b433de) (MetaMask) to [Polygon](https://polygonscan.com/tx/0x31ab8838d41a380a18fd976128e5c660382f4d136ffba26aed2bce306b658cf1) (MetaMask) with wstETH Bridge route Remaining issue: [#2086](https://github.com/wormhole-foundation/wormhole-connect/issues/2086).
- wstETH from [Polygon](https://polygonscan.com/tx/0x6780ee1f1d8109736d3b2699739fe1ae42e1609e4fd02775a85bb966d09e6528) (MetaMask) to [Arbitrum](https://arbiscan.io/tx/0x41194abe60566a5517cb25c43c7ab53ee486e81fc9c6a47047353cafa311772e) (MetaMask) with wstETH Bridge route
- wstETH from [Arbitrum](https://arbiscan.io/tx/0xd622385d4ac093f85bd51c7b37dd3a82cbf5ed5dd18c805eaa4e28300f8a856c) (MetaMask) to [Optimism](https://optimistic.etherscan.io/tx/0xe4faf5624e24e91c5f9de67c062e73db2aa7007583f33929413737b3c286bdf7) (MetaMask) with wstETH Bridge route
- WGLMR from [Aptos](https://explorer.aptoslabs.com/txn/0x960bbd179dc6f8cd29144614a3c35d01d525ed03c922db33d8dc66b62f3aef13?network=mainnet) (Spika) to [BSC](https://bscscan.com/tx/0x52258caac752cb9750530d5bc3d9fd944007071af1b8c0b4e45d9c6a5fb34b48) (MetaMask) with Manual Bridge route
- USDC from [Base](https://basescan.org/tx/0x01bc39c8aeadab3c3c335ceeec3ba53add669b8cf1129813be626de9dce3b57d) (MetaMask) to [Klaytn](https://klaytnscope.com/tx/0x9f2e46fd8dd0d5b40ab28cfc3d611db7999a8fb87b1dd9c35b08e5899ca0b969) (MetaMask) with Manual Bridge route

2. Issue is no longer reproducible on https://portalbridge.com/ [Mainnet] when sending:

- BONK from [Solana](https://explorer.solana.com/tx/54zos9uyCXubGgkpr3qm933C9LKcUsNAXnRE4qpXmMiuQzHr1kPMf8BF5QzoSoB6KwR7Gm7GKtDJ1jEZXbnfHiyK) (Phantom) to [BSC](https://bscscan.com/tx/0x1f4c04b434323c63127db81a5820094d0aceaaedbf546b149197059b8a64746a) (MetaMask) with Manual Bridge route.
- WETH (Polygon) from [Polygon](https://polygonscan.com/tx/0x695213740e22b89774d7896c1865c2c2202907c69341e1a37e1d420659fe57cf) (MetaMask) to [BSC](https://bscscan.com/tx/0x06ced0bbf5a2247c2753befd3ce422749f9128c45fa2b6e640e330b7b00d2e55) (MetaMask) with ETH Bridge route

3. Issue is still reproducible on https://wormhole-connect.netlify.app/  [Testnet] when sending asset to Sui network, scenario “wKLAY from [Fantom](https://testnet.ftmscan.com/tx/0x841145d2220e091ecdd21819b81718386ae378344fe052e86a438df9fa1aabfe) (MetaMask) to [Sui](https://suiscan.xyz/testnet/tx/7EPDxqcsqZH4zDC9XeoY3zsaRH5VQSr9VeQdEdzaES7p) (Sui Wallet)”. Ticket [#2189](https://github.com/wormhole-foundation/wormhole-connect/issues/2189)  

4. Issue is still reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending asset to Sui network. Ticket [#2189](https://github.com/wormhole-foundation/wormhole-connect/issues/2189)  


- SUI from [Evmos](https://www.mintscan.io/evmos/tx/D1F4ACB5C4E2BC7391A0A73E3BCCF05C02CD91D2BB70F01B45828282FD3BE7F9) (Leap) to [Sui](https://suiscan.xyz/tx/9Au57VTD5uVYYSziiS7c8L9wPA2JM9egYCF5GFA7gH7m) (Sui Wallet). 
- SUI from [BSC](https://bscscan.com/tx/0xe9ddf659220948ca9b633ecb5f6e160a4fbf5bdd0fadf4872d4be6a8356839d7) (MetaMask) to [Sui](https://suiscan.xyz/tx/CUVxWqeQNFnJcE8BrQZuWd8sXKVPso4QeSZwH3aH8xnp) (Sui Wallet) 
- wKLAY from [Blast](https://blastscan.io/tx/0xa971e43ce0ee7aeabe7f8733212ac5dc9d1a0ae00b0df418a7873d12eb054916) (MetaMask) to [Sui](https://suiscan.xyz/tx/5wbHM2fJzUZctVhKVxQtyQXVQaCvtdWnyWqdfsFvX8tL) (Sui Wallet)


5. Issue is still reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending asset to Avalanche network, scenario “PYTH transfer from [Solana](https://explorer.solana.com/tx/2rnScHeKJErsnzwW8uBFxnW4X4YLNtd1xvwDhSnGPZiFmKKjY6YybRZKKhe2Ez88UtsMgc9XpdMckrvx9i3J9ZCw) (Phantom) to [Avalanche](https://avascan.info/blockchain/c/tx/0x5079cbb0bf32dcea39d0329ff1f3f180669c0b4d733d549844577ca9014174da) (MetaMask) with Manual Bridge route” . Ticket [#2191](https://github.com/wormhole-foundation/wormhole-connect/issues/2191)

Ticket is closed.

**Closed as completed by tsadovska** 2024-06-14 15:26 UTC
Labels: p2
