### ISSUE TITLE
[QA] Cannot start transactions to BSC

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#670] opened 2023-06-07 07:13 UTC
Preconditions:
Metamask wallet is connected
Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98
Tested from: https://feature-sei--wormhole-connect.netlify.app/#

Steps:
1. Prepare to send asset from any Network to BSC (e.g. 0.2 CELO from Alfajores to BSC)
2. Observe the fields
3. Try to press Approve and proceed with transaction

Actual result: The fields are left inactive and user cannot press Approve and proceed with transaction

Expected result: Transaction moves to the next screen and is complete

Comments: Fields change to active if BSC is changed to different Network and changed back to BSC.

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/96b00702-6045-4d33-b83f-3a2d6b367776

<img width="1322" alt="Screenshot 2023-06-07 at 10 11 16" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/b7aacf57-9838-4dd7-9bb6-b4b543bea157">

**Comment by M-Picco** [comment] 2023-06-08 14:58
Closing this and #672 since they seem to be due to issues with the testnet BSC RPC node

**Closed as completed by M-Picco** 2023-06-08 14:58 UTC
Labels: p1

**Comment by tsadovska** [comment] 2023-06-25 07:13
Issue is reproducible on https://wormhole-connect.netlify.app/ when user sends APT from Aptos (in my case from Spika wallet) to BSC (Metamask wallet).


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/65b72dcc-ac50-450e-9027-7fa40ab7e099
