### ISSUE TITLE
[QA] Connect wallet screen is empty and no message is displayed for the user when Sui Wallet Extension is disabled and Sui network is selected

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#569] opened 2023-05-05 11:29 UTC
#### Build:
https://wormhole-connect.netlify.app/ 

#### Precondition:
Sui Wallet Extension is disabled.

#### Steps:

1. Select Sui network
2. Click “Connect wallet” button

#### Actual result:

- Connect wallet screen is empty
- No message is displayed

#### Expected result:
Message is shown for the user.

#### Note:
Linked #558

#### Devices:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 112.0.5615.121 (Official Build) (x86_64)

#### Attachment:
![Screenshot 2023-05-05 at 13 45 09](https://user-images.githubusercontent.com/10746654/236446222-e4aaba7c-34b4-4d62-b778-b7e3311c73da.png)

**Comment by anondev2323** [comment] 2023-05-05 15:38
Duplicate of #558

**Closed as completed by anondev2323** 2023-05-05 15:38 UTC
Labels: p2
