### ISSUE TITLE
[QA]No notification to refresh the page when Rabby wallet is enabled/disabled

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1802] opened 2024-03-15 14:58 UTC
Preconditions:
Rabby wallet disabled

Environment:
OS: macOS Ventura 13.0.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://deploy-preview-1795--wormhole-connect-mainnet.netlify.app/# 

Steps:
1. Click on Rabby wallet extension
2. Enable Rabby wallet
3. Observe

Actual result: No pop-up message to refresh the web page is shown when enabling/disabling Rabby wallet

Expected result: Pop-up notification to refresh the page is shown when Rabby wallet is enabled/disabled 

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/788ac372-699c-4ceb-80e0-4f1febae376e

Pop-up notification:
<img width="390" alt="Screenshot 2024-03-15 at 16 54 30" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1b1c9067-bbcc-4c65-8bf8-dde450a58a43">

**Comment by AigaD** [comment] 2024-03-18 08:01
Tested from: https://deploy-preview-1795--wormhole-connect-mainnet.netlify.app/#
Tested OK. Closing the ticket.
Notification that Rabby wallet is enabled/disabled is shown and user is able to refresh the page using the link provided in pop-up message.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d148b098-b98a-4943-96a4-57db1491f33f

**Comment by AigaD** [comment] 2024-03-20 15:22
Reopening.
Tested from: https://deploy-preview-1274--wormhole-connect-mainnet.netlify.app/#
No notification to refresh page, when enabling/disabling Rabby wallet
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3e4891ed-4ff2-4a03-80be-385b89023d0e

**Comment by AigaD** [comment] 2024-03-21 08:15
Tested from: https://deploy-preview-1274--wormhole-connect-mainnet.netlify.app/#
Closing as this is no longer reproduced, pop-up message to refresh the page when Rabby wallet is enabled/disabled is shown.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/606f344e-7ba7-44b4-afd1-6c062c473082

**Comment by AigaD** [comment] 2024-04-04 06:21
Re-opening.
Tested from: https://deploy-preview-1674--wormhole-connect.netlify.app/#
No notification that wallet needs to be refreshed.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a2d7d846-073d-4e8d-99b9-a202ac358cc4

**Comment by AigaD** [comment] 2024-04-08 14:37
Reproduced from: https://wormhole-connect.netlify.app/#
No notification to refresh the page when enabling/disabling Rabby wallet.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/93b56a16-12dd-4675-b685-e19dfbc83af7

**Comment by AigaD** [comment] 2024-04-12 08:00
Reproduced from: https://deploy-preview-1869--wormhole-connect-mainnet.netlify.app/#

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/293fbcd4-c9d4-45c4-8587-82ce263ac3b0

**Comment by AigaD** [comment] 2024-04-15 16:37
Tested from: https://testnet.portalbridge.com/ed4e22522f/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/253aba1d-15c3-48ad-93d0-9aae2872f30b

**Comment by AigaD** [comment] 2024-05-07 08:13
Reproduced from: https://preview.portalbridge.com/bceadc8c64/#

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0d4a9488-519c-4673-94c9-f172d5d775d3

**Comment by AigaD** [comment] 2024-05-23 06:28
Tested from: https://deploy-preview-2113--wormhole-connect-mainnet.netlify.app/#
No notification that user should refresh the page when Rabby wallet is enabled
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d0310fa6-e0a3-4d8e-b1db-461f378fda31

**Comment by agodlevska** [comment] 2024-06-10 10:27
Tested on https://wormhole-connect-mainnet.netlify.app/, https://wormhole-connect.netlify.app/ and https://portalbridge.com/.
The page refresh notification pop-up is displayed when the Rabby wallet is enabled/disabled on each link.
Closing the ticket. 

Attachments:
<img width="1439" alt="Screenshot 2024-06-10 at 13 18 20" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/b2815311-395f-4347-be1a-04a889480238">

<img width="1440" alt="Screenshot 2024-06-10 at 13 17 47" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/f539d04a-dfa8-4ed1-a99f-567586da3261">

**Comment by agodlevska** [comment] 2024-08-28 06:46
Reopening the ticket. 
Sometimes issue reproducible on [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZERGwPYm56iANoA6cQBEAogDEAggFUAMgBUA%2BpQDyClVIDKBMAFk0ATzTRK%2FQQF0QAXxAggA). 

Attachment: 

https://github.com/user-attachments/assets/e1a6fd8c-4e59-4736-8086-a3390da386c0

**Comment by sebastianscatularo** [comment] 2024-09-13 11:54
unable to reproduce it

<img width="1576" alt="image" src="https://github.com/user-attachments/assets/e055b066-e565-464b-9d0e-17a5255e17c5">

**Comment by agodlevska** [comment] 2024-09-13 14:27
Re-checked on https://preview.portalbridge.com/b1f3c5115d/ and [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D). 
Issue is no longer reproducible. 
Pop-up notification to refresh the page is shown when Rabby wallet is enabled/disabled.

Closing the ticket.

**Closed as completed** 2024-09-13 14:27 UTC
Labels: p2, wallet, connect v2
