### ISSUE TITLE
[QA] White field shows when decreasing page zoom

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1077] opened 2023-10-05 09:51 UTC
Preconditions: none

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Tested from: 
https://wormhole-connect.netlify.app/ - Tested NOK
https://deploy-preview-1058--wormhole-connect-mainnet.netlify.app/# - Tested OK

Steps:
1. Open https://wormhole-connect.netlify.app/
2. Set the page zoom lower than 100% (during my test 75%)
3. Observe

Actual result: When lowering the page zoom white field shows on the page

Expected result: Page corresponds to page zoom decrease 

Attachment:
Page zoom 75%:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/11c24669-b1da-4106-89ec-550129cd0aee

Page zoom 100%:

<img width="1433" alt="Screenshot 2023-10-05 at 15 55 58" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/9b3b0925-3f40-47c1-aed3-f8b10c03490b">

**Comment by tsadovska** [comment] 2023-10-05 13:08
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet].

**Comment by evan-gray** [comment] 2023-10-05 13:28
Thanks for writing this up! This was due to a change I made to fix the widget display in integrator sites (the default background would always be the height of the user's window, but all others appeared like this). I expect that integrators would have their site display however they would like, but I will fix the demo page to take this into account.

**Comment by AigaD** [comment] 2023-10-06 05:34
Re-opening the ticket. 
Sorry, but can we leave the ticket open until the design is fixed completely? Now instead of white background there is black, on Resume transaction the Wormhole-connect page design does not fill in all the page and naming "Demo App" is now present both for https://wormhole-connect.netlify.app/# and https://wormhole-connect-mainnet.netlify.app/

Attachment:

<img width="1414" alt="Screenshot 2023-10-06 at 08 35 20" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/76d415c1-ca59-4f0c-9b21-0a977707536d">


<img width="1423" alt="Screenshot 2023-10-06 at 08 34 31" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/63b0495a-5fde-4917-8365-da4c6793be47">

**Comment by AigaD** [comment] 2024-03-21 09:26
Tested from: https://wormhole-connect-mainnet.netlify.app/
Background now shows black and when page is decreased blue colors are shown at some parts of design
Attachment:
<img width="1385" alt="Screenshot 2024-03-21 at 11 25 01" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5ff47ffe-7221-4555-893e-82d8131c8d2a">

**Comment by tsadovska** [comment] 2024-08-19 10:07
The design of https://wormhole-connect-mainnet.netlify.app/ looks good.
Issue is not reproducible after redesign.

Closing the ticket.

**Closed as completed by tsadovska** 2024-08-19 10:07 UTC
Labels: design, p2
