### ISSUE TITLE
[QA] Asset balance is not fully visible

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1123] opened 2023-10-18 07:48 UTC
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS 12.7 and Google Chrome Version 118.0.5993.88 (Official Build) (x86_64).

Precondition:
User has  high asset balance

Steps:
1. Connect wallet
2. Select network
3. Select asset with high balance
4. Check if asset balance is fully visible

![Screenshot 2023-10-18 at 10 47 30](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/9c8dec14-da49-42de-9d3c-e9c1e486e806)

![Screenshot 2023-10-18 at 10 47 08](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/56c3d4ef-500e-438b-b0f3-37c90a1960b4)

## What is the expected/desired behavior
Asset balance is fully visible.

**Comment by tsadovska** [comment] 2023-12-27 16:27
Issue is also reproducible on https://testnet.portalbridge.com/4adb101c39/ [Testnet].

**Comment by tsadovska** [comment] 2024-02-23 16:23
Issue is also reproducible with BONK asset on https://wormhole-connect-mainnet.netlify.app/ and 
https://preview.portalbridge.com/7246284e5d/. Original ticket: https://github.com/wormhole-foundation/wormhole-connect/issues/1701. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/0de35d73-1233-41d2-a2de-9301c2e24311)

**Comment by agodlevska** [comment] 2024-06-11 10:09
Checked on https://portalbridge.com/
The issue is still reproducible. 

Attachment:
<img width="696" alt="Screenshot 2024-06-11 at 13 07 39" src="https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/8891622b-a3ad-4cda-a86b-ba7ad8b12aeb">

**Comment by agodlevska** [comment] 2024-07-31 07:37
Issue is still reproducible on https://wormhole-connect-mainnet.netlify.app/, https://wormhole-connect.netlify.app/ and  https://portalbridge.com/.

Attachments:
![Screenshot 2024-07-31 at 10 34 24](https://github.com/user-attachments/assets/443a0ce5-674a-4531-8fc2-a2c468f58fa2)
![Screenshot 2024-07-31 at 10 34 33](https://github.com/user-attachments/assets/c99c165f-8c5d-43fc-980c-aacf17879f52)

**Comment by agodlevska** [comment] 2024-09-23 09:11
After redesign, issue is no longer reproducible on https://portalbridge.com/ and https://wormhole-connect-mainnet.netlify.app/. 
Closing the ticket. 

Attachment:
<img width="511" alt="Screenshot 2024-09-23 at 12 07 08" src="https://github.com/user-attachments/assets/e531e342-b118-443b-bc3a-7e0532f02e6a">

**Closed as completed by agodlevska** 2024-09-23 09:11 UTC
Labels: p2
