### ISSUE TITLE
[QA] [Testnet] Sometimes cannot change slider position when sending SUI from Sui to BSC

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2102] opened 2024-05-20 15:16 UTC
## Describe the current behavior in detail
Checked on [testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDACIAjAJwEsATAc0gBFIAzAQwFcAbFdIxUCCEzIB7ALYA5HAHdhZANaIk6NhXyEIKYZJQz5ikugDGagWE1yYigMoBVAJImwAXxBOgA%3D) with macOS Sonoma 14.4.1 and Google Chrome Version 125.0.6422.61 (Official Build) (arm64).

Preconditions:
Testnet network is selected in Sui wallet.

Steps:
1. Prepare to send 2 SUI from Sui (Sui wallet) to BSC (MetaMask)
2. Enable "Native gas" section
3. Change slider position

Actual result: Cannot change slider position.
Expected result: Slider position can be changed. 

## Notes/ Attachments

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/916ea537-001c-4c8a-abc4-851936520949

**Comment by agodlevska** [comment] 2024-07-26 08:01
The issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/.
User can change slider position when sending SUI from Sui to BSC, issue reproducibility: 0/10.
Closing the ticket.

Attachment:

https://github.com/user-attachments/assets/21823ed8-eda4-4fb3-aef5-9de80d63f3a6

**Closed as completed by agodlevska** 2024-07-26 08:01 UTC
Labels: p2
