### ISSUE TITLE
[QA] [Testnet] Cannot change slider position when sending FTM from Fantom to BSC

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1661] opened 2024-02-14 14:03 UTC
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS and Google Chrome.

Steps:
1. Select "Fantom" as source chain
2. Select "BSC" as destination chain
3. Connect "MetaMask" in From and To sections
4. Select FTM asset
5. Enter Amount, 10
6. Enable "Native gas" section
7. Change slider position
 
Actual result: Cannot change slider position.

Reproducibility: 2/5

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/533e3e54-111a-420e-88d7-40dfa87fa537

## What is the expected/desired behavior
User can change slider position when sending FTM from Fantom to BSC.

**Comment by AigaD** [comment] 2024-03-18 11:27
Tested from: https://wormhole-connect.netlify.app/#

User is not able to change slider position for Native gas when sending FTM asset from Fantom to BSC. One of four tests failed.

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e2483230-14cd-4a47-b1f9-2b187c2f7a21

**Comment by agodlevska** [comment] 2024-07-24 09:11
The issue is no longer reproducible on https://wormhole-connect.netlify.app/.
User can change slider position when sending FTM from Fantom to BSC, issue reproducibility: 0/10. 
Closing the ticket.

Attachment:

https://github.com/user-attachments/assets/c759170d-ba0a-4638-851f-140ea6c43398

**Closed as completed by agodlevska** 2024-07-24 09:11 UTC
Labels: p2
