### ISSUE TITLE
[QA] Warning "No routes found" is displayed when minimum required amount is entered

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2765] opened 2024-09-30 08:41 UTC
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/?config=N4KAdgpgLg7g9gJwNYC4AEAiAsgQwJZiRQYA0ICcArlBAM7oDauAnjmAEpU1YDCAKgAUAuiAC%2BQA.

Custom config:
```
{
network: "Mainnet",
routes: [MayanRouteMCTP]
}
```

Steps:
1. Prepare to swap ETH from Ethereum (MetaMask) to POL on Polygon (MetaMask) with MayanRouteMCTP
2. Enter a small amount, 0.000001
3. Check minimal required amount and change the amount, in my case 0.0043
4. Observe if route is available

Actual result: Warning "No routes found for this transaction." is displayed. The warning is displayed even when a higher amount is entered, 0.015011. 

Expected result: 
* If the route is not available up to a certain amount, the "minimum required amount" warning should be displayed. The route is shown when the minimum required amount is entered.
* If the route is not available for any amount entered, the "minimum required amount" warning should not be displayed.

## Notes/ Attachments

https://github.com/user-attachments/assets/f69a3410-5351-41c3-b613-6db97f67bfb3

**Comment by Wesleyleung** [comment] 2024-10-24 03:14
This issue no longer seems to be reproducible. Closing

**Closed as completed by Wesleyleung** 2024-10-24 03:14 UTC
Labels: p2, connect v2
