### ISSUE TITLE
[QA][Mainnet] Cannot connect to Sui Metamask Snap when OKX wallet extension is enabled

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1544] opened 2024-01-24 15:06 UTC
Preconditions:
OKX wallet disabled in extension
Console open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 120.0.6099.234

Tested from: https://wormhole-connect-mainnet.netlify.app/# and https://preview.portal-bridge-ui.pages.dev/c0216a7edf/#

Steps:
1. Connect to Sui network
2. Open Connect Wallet
3. Select Sui Metamask Snap
4. Observe
5. In extensions enable OKX wallet
6. Refresh Wormhole connect/Portal Bridge page
7. Repeat steps 1-3

Actual result: Cannot connect to Sui Metamask Snap when OKX wallet extension is enabled, console shows error: `"The method 'wallet_getSnaps' does not exist / is not available."`

Expected result: Wallet is connected

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c773032a-905b-482f-8c9a-fbb111927827

**Comment by tsadovska** [comment] 2024-01-30 08:20
Closing as duplicate of https://github.com/wormhole-foundation/wormhole-connect/issues/1510.

**Closed as not planned by tsadovska** 2024-01-30 08:20 UTC
Labels: p2
