### ISSUE TITLE
[QA] Glitch in the wallet list when Connect Wallet is opened

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#308] opened 2023-04-11 06:32 UTC
Preconditions:
Wormhole-connect is opened

Environment: Galaxy S22+, Android v12, Chrome v110.0.5481.65

Steps:
1. Select wallet at sending From section
2. Select Network at sending From section (e.g. Goerli)
3. Now click on Connect Wallet at sending To section
4. Observe when the list is opened

Actual result: There is a slight glitch where wallets change position in the list when the Select Wallet is opened at sending To section.

Expected result: Wallets in the list do not change position.

Attachment:

https://user-images.githubusercontent.com/91047061/231074361-02584b61-cb9d-4ff6-accb-db90a7e5eefb.mp4

**Comment by AigaD** [comment] 2023-10-03 05:59
This is still reproducible. Tested from: https://wormhole-connect.netlify.app/#
When first connecting Networks and the wallets, Metamask wallet changes position in wallet list.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/093c2902-f726-413e-91ff-c2f7a8274014

**Comment by tsadovska** [comment] 2023-10-05 18:04
Closing as duplicate of #252.

**Closed by tsadovska** 2023-10-05 18:04 UTC
Labels: p2
