### ISSUE TITLE
[QA] [Testnet] Cannot change slider position when sending CELO from Alfajores

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1911] opened 2024-04-10 16:31 UTC
## Describe the current behavior in detail
Checked on https://wormhole-connect.netlify.app/ [Testnet] with macOS and Google Chrome. 

Steps:
1. Select Alfajores network as source chain
2. Select BSC network as destination chain
3. Connect MetaMask wallets in "From" and "To" sections
4. Select CELO asset
5. Enter Amount - 5
6. Enable "Native gas" section 
7. Change slider position

Actual result: Cannot change slider position.

Reproducibility: 4/7.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/11a3bb84-4854-4c8f-810e-f01e9e5ccbd2

## What is the expected/desired behavior
User can change slider position when sending CELO from Alfajores to BSC.

**Comment by tsadovska** [comment] 2024-05-10 11:07
Reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending CELO from Celo (MetaMask) to Moonbase (MetaMask).


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1269dbd8-6fc0-4f75-b131-7cdac55cbdd3

**Comment by agodlevska** [comment] 2024-07-08 13:35
Checked on https://wormhole-connect.netlify.app/.

The issue is still reproducible. 
Sending 6 CELO from Alfajores (MetaMask) to BSC (MetaMask).

Reproducibility: 5/8.

Attachment: 

https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/4958da51-3aec-40dc-a8d8-81603257a85d

**Comment by agodlevska** [comment] 2024-08-14 13:08
Checked on https://wormhole-connect.netlify.app/.
The issue is no longer reproducible.
User can change slider position when sending CELO from Alfajores to BSC, issue reproducibility: 0/10.
Closing the ticket.

Attachment:

https://github.com/user-attachments/assets/dda6c172-fa4f-4220-b08d-5af78c93c7b9

**Closed as completed by agodlevska** 2024-08-14 13:08 UTC
Labels: p2
