### ISSUE TITLE
[QA]Higher token balances are cut on Home screen

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1701] opened 2024-02-23 10:40 UTC
Preconditions:
Solana supported wallet connected at sending From section
BONK asset balance during test 16593645.9713 BONK

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/#
https://preview.portalbridge.com/7246284e5d/

Steps:
1. Select Solana Network
2. From Asset list select BONK
3. Observe balance shown on Home screen

Actual result: Balance is not fully shown, after comma some values are cut off

Expected result / Improvement: Perhaps possible to reduce font size to fit all balance in the field so it would not be cut off

Attachment:

![Screenshot 2024-02-23 at 12 33 54](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/cec1a0ce-61e8-4b88-bc13-40939fcf6ee4)
![Screenshot 2024-02-23 at 12 33 28](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/dd1f1521-b46d-4e78-b397-f3fb54d7daed)

**Comment by tsadovska** [comment] 2024-02-23 16:24
Closing as duplicate of https://github.com/wormhole-foundation/wormhole-connect/issues/1123.

**Closed as not planned by tsadovska** 2024-02-23 16:24 UTC
Labels: p2
