### ISSUE TITLE
[QA] Wallet disconnects at one section if connecting using OKX wallet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1945] opened 2024-04-17 10:23 UTC
Precondition:
OKX wallet extension enabled

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://testnet.portalbridge.com/ed4e22522f/

Steps:
1. Connect Sepolia Network at sending From section
2. Click on Connect wallet
3. Select Metamask
4. On OKX wallet pop-up select Metamask
5. At sending To section select Solana network
6. Click on Connect wallet
7. Select OKX wallet
8. Observe wallet at sending From section

Actual result: Metamask wallet at sending Form section disconnects when OKX wallet to Solana network is connected

Expected result: Wallets are left connected

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/deddd565-6357-45e7-a5a4-cdd9504c3933

**Comment by agodlevska** [comment] 2024-10-16 12:03
Checked on https://wormhole-connect.netlify.app/. 
The issue is no longer relevant after the redesign, OKX wallet is not in the list for Solana network. 

Closing the ticket. 

Attachment:
<img width="1440" alt="Screenshot 2024-10-16 at 15 00 15" src="https://github.com/user-attachments/assets/5b1c8d4c-a75a-4cbc-b277-986904c41905">

**Closed as not planned by agodlevska** 2024-10-16 12:03 UTC
Labels: p2
