### ISSUE TITLE
[QA] [Testnet] Amount field on Wormholescan should have more decimals after comma

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1957] opened 2024-04-18 14:36 UTC
## Describe the current behavior in detail
Checked on https://testnet.portalbridge.com/ed4e22522f/ [Testnet] (Portal Bridge: 0.2.12, Wormhole Connect: 0.3.4-beta.4-development) with macOS Sonoma 14.4.1 and Chrome Version 124.0.6367.62 (Official Build) (arm64)

Steps:
1. Send 0.0002 Ws from Sepolia (MetaMask) to Alfajores (MetaMask)
2. Click on [View on Wormholescan](https://wormholescan.io/#/tx/0x5a9f2428a4fca6235a1db1287b5accb9b23030b92a344792bb14f01a5c550ba1?network=TESTNET) link on Redeem screen
3. Check Amount field

Actual results:
* Sending amount is shown as 0.00 [Ws](https://sepolia.etherscan.io/token/0x738141eff659625f2ead4feecdfcd94155c67f18) on [Wormholescan](https://wormholescan.io/#/tx/0x5a9f2428a4fca6235a1db1287b5accb9b23030b92a344792bb14f01a5c550ba1?network=TESTNET) 
* Send from tx: [Etherscan](https://sepolia.etherscan.io/tx/0x5a9f2428a4fca6235a1db1287b5accb9b23030b92a344792bb14f01a5c550ba1)
* Send to tx: [Celo Explorer](https://explorer.celo.org/alfajores/tx/0x10f107f847178b988223bcf6aeb0e0a2636e1e9258b48cc43083562f1c6d6943)

![Screenshot 2024-04-18 at 17 34 57](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2d90395e-d7e9-44c5-b717-7d2fc7aea405)

![Screenshot 2024-04-18 at 17 35 24](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/7a098bcd-84c9-449f-91c5-484a144d1225)

## What is the expected/desired behavior
Sending amount is 0.0002 [Ws](https://sepolia.etherscan.io/token/0x738141eff659625f2ead4feecdfcd94155c67f18).

**Comment by agodlevska** [comment] 2024-07-30 08:46
The issue is no reproducible on https://wormhole-connect.netlify.app/.

- Send from tx: [BSC](https://testnet.bscscan.com/tx/0x32494f551855e8851fa95df569d1e83c0fa2b6f39cfc39075ecb132060009baa)
- Send to tx: [Fantom](https://testnet.ftmscan.com/tx/0xb9beffa3c6ab835165532d721a9bb8b0b553aa9c89b455d83ead29e03cbabdd1)
- [Wormholescan](https://wormholescan.io/#/tx/0x32494f551855e8851fa95df569d1e83c0fa2b6f39cfc39075ecb132060009baa?network=TESTNET)

Also, the case described in the ticket is no longer reproducible and the amount is displayed correctly.
Closing the ticket.

Attachment:
![Screenshot 2024-07-30 at 11 39 02](https://github.com/user-attachments/assets/7b8afc26-7612-4a97-821f-4a74f5eaca4b)

**Closed as completed by agodlevska** 2024-07-30 08:46 UTC
Labels: p2
