### ISSUE TITLE
[QA] Possible to go around token registration

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1156] opened 2023-10-25 06:55 UTC
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Tested from: https://wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.1 USDT from Moonbase to Base Goerli
2. Observe that token needs to be registered message is shown
3. Swap Moonbase and Base Goerli places
4. Observe that fields are active, "Approve and proceed with transaction" button is active although no USDT balance is available for Base Goerli
5. Click "Approve and proceed with transaction" button
6. Reject the transaction in the wallet pop-up
7. Swap again places for Networks
8. Observe
9. Click "Approve and proceed with transaction" button

Actual result: When transaction fields are swapped places fields become active and the token registration message is no longer shown. User is able to continue with transaction and the transaction fails at Claim, reason `Error: call revert exception; VM Exception while processing transaction: reverted with reason string "no wrapper for this token created yet"`

Expected result: Field should not be shown/active if there is no available token balance, token registration should be shown for relevant transactions

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/982dd751-7bee-4561-b583-70c39ba87fd1

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/19191ea5-d637-4848-812c-fbc1d492e2b4

**Comment by tsadovska** [comment] 2024-08-26 12:55
Scenario is no longer reproducible, because Base Goerli network is deprecated. 
Closing the ticket.

**Closed as completed by tsadovska** 2024-08-26 12:55 UTC
Labels: p2
