### ISSUE TITLE
[QA]Fee estimates should have more decimals behind comma Native token transfer

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1941] opened 2024-04-17 09:03 UTC
Precondition:
Metamask wallet connected

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
https://testnet.portalbridge.com/ed4e22522f/

Steps:
1. Prepare to send 0.01 Ws from Base Sepolia to Optimism Sepolia
2. Select Manual Native token transfer route
3. Observe gas fee estimates in Preview section
4. Click on Approve and proceed with transaction
5. Observe Gas fee on Wallet pop-ups

Actual result: In preview section Gas fee estimates are shown as 0 ETH (Base Sepolia) & 0 ETH (Optimism Sepolia)
($0.00) & ($0.00)

Expected result: Gas fee estimate should be shown, even if smaller amount is reduced from users account (0.0004 ETH gas fee estimate should be shown)

Attachment:
<img width="1044" alt="Screenshot 2024-04-17 at 11 58 30" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/08b1e0f8-cc0c-43f9-a2cc-e8f55c6bd8b8">
<img width="984" alt="Screenshot 2024-04-17 at 11 57 27" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/015cffc0-1e0a-4cb0-a23c-01301a8f2d99">
<img width="1031" alt="Screenshot 2024-04-17 at 11 57 11" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e969e352-f346-4718-916d-a984114a383d">

**Comment by agodlevska** [comment] 2024-10-16 09:23
The issue is no longer relevant after the redesign, the fields are named differently and all errors concerning them have been created separately. 
Closing the ticket.

**Closed as not planned by agodlevska** 2024-10-16 09:23 UTC
Labels: p2
