### ISSUE TITLE
[QA][Mainnet] Occasionally cannot change slider position for transaction BSC -> Base

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2103] opened 2024-05-20 15:35 UTC
Precondition:
{
  env: 'mainnet',
  "bridgeDefaults": {
    fromNetwork: 'bsc',
    toNetwork: 'base',
    token: '',
  }
}

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
[Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJGW4BjQsQi4Rk3DPmKyabpHWCwWuTEWmwAXxC2gA%3D%3D%3D#)

Steps:
1. Prepare to send 0.01 BNB from BSC to Base
2. Select Automatic Route
3. Expand Native gas section
4. Try to change the slider position

Actual result: Occasionally Native gas slider cannot be changed

Expected result: Native gas slider can be changed every time

Reproducibility: 2/4

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7cd1b5dd-ec9a-47fb-a4ad-87e16e76df00

**Comment by agodlevska** [comment] 2024-07-26 07:54
The issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/.
User can change slider position when sending BNB from BSC to Base, issue reproducibility: 0/10.
Closing the ticket.

Attachment:

https://github.com/user-attachments/assets/491d1234-a95c-4348-9854-ee11e899c61e

**Closed as completed by agodlevska** 2024-07-26 07:54 UTC
Labels: p2
