### ISSUE TITLE
[QA][Mainnet]Cannot create associated account for transaction to Solana

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1687] opened 2024-02-20 07:53 UTC
Preconditions:
Rabby wallet connected at sending From section
Backpack wallet connected at sending To section
Console is opened

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/# - Tested NOK
https://wormhole-connect.netlify.app/ - Tested NOK

Steps:
1. Prepare to send 0.01 GLMR from Moonbeam to Solana
2. Observe that associated account has to be created 
3. Click on Create account
4. Observe

Actual result: Create account is loading for a long time eventually failing with error `TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed.`

Expected result: Associated account is created

Attachment:
<img width="1327" alt="Screenshot 2024-02-20 at 09 33 21" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/75bb02bc-edd4-4b95-b45e-b3102dfca89c">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3a1f03a5-9ea8-45cd-aee8-e3c0ca80b415

**Comment by AigaD** [comment] 2024-02-27 10:37
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Failing to create associated account for transaction USDT from Osmosis (Leap) to Solana (Phantom)
Account creation fails with reason `main.js:499 TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds.` and if trying to click again on Create account, the button is not reacting.

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d4351a2e-2319-41da-ba0b-cc88e0a6a796


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7d147982-1b5a-48c4-b20d-bc902ceaff90

**Comment by bangjelkoski** [comment] 2024-02-29 18:11
Any luck resolving this?

**Comment by tsadovska** [comment] 2024-03-05 15:26
Issue is reproducible on https://portalbridge.com/ [Mainnet] when sending USDC (Avalanche) from Evmos (Leap) to Solana (Phantom). 

Error after clicking on "Create account" link:
```
TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 65jaYtYc4sQsuEoo3zptSCB1voXDhKbTjeQbxu32JuRTypK5b8JTXacfRvQ2CyPorFXcKb1F6Hw9qYdBFLKopACH using the Solana Explorer or CLI tools.
    at Connection$1.confirmTransactionUsingLegacyTimeoutStrategy (main.js:171:61258)
    at async Connection$1.confirmTransaction (main.js:171:56700)
    at async O.sendTransaction (solana-mxqvqbiT.js:1:40048)
    at async Ie (solana-mxqvqbiT.js:1:48158)
    at async signAndSendTransaction (main.js:322:774354)
    at async Object.createAssociatedTokenAccount (main.js:499:168808)
    at async sn (main.js:499:166852)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a83d8ed5-eaa7-4941-84d3-b1dfb1b7654f)

**Comment by AigaD** [comment] 2024-03-15 11:04
Reproduced from: https://deploy-preview-1795--wormhole-connect-mainnet.netlify.app/#
Cannot create associated account after transaction timeout error is shown and user again tries to create account. After it seems that user has failed to create associated account, is user refreshes the page and fills in the fields with the same assets as before, Create associated account is no longer shown
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5049a6d4-9d16-4e7b-9e71-8b4f6bc63e81

**Comment by tsadovska** [comment] 2024-03-15 15:43
Reproducible on https://deploy-preview-1795--wormhole-connect-mainnet.netlify.app/ [Mainnet] when 0.0001 WSOL from Injective (Leap) to Solana (Clover). 

Error after clicking on "create account" link:

```
WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 1: custom program error: 0x1
    at Ht.sendTransaction (solana-3Sa-HcsX.js:1:6027)
    at async O.sendTransaction (solana-3Sa-HcsX.js:1:39962)
    at async Ie (solana-3Sa-HcsX.js:1:48158)
    at async signAndSendTransaction (main.js:322:777245)
    at async Object.createAssociatedTokenAccount (main.js:522:168007)
    at async sn (main.js:522:166051)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5589a30f-95a3-43d3-91b9-23972013529a)

**Comment by AigaD** [comment] 2024-03-20 16:52
Tested from: https://deploy-preview-1274--wormhole-connect-mainnet.netlify.app/#
Creating associated account for transaction USDC from Avalanche/Arbitrum/Base to Solana (new account Phantom) fails, reason `WalletSendTransactionError: Unexpected error`
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3a9e96cf-e8a2-4819-885a-90544c4b0187

<img width="1292" alt="Screenshot 2024-03-20 at 18 54 24" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/24344560-5d87-42d3-9e84-fcd9b2eed964">

**Comment by Eiei070922** [comment] 2024-03-20 23:28
Hello, I'm Thidarat. I'd like to apologize to the team for what I didn't study before coming to play crypto. In the case of transactions on etherscan, I didn't know that the transactions belonged to other people. I understand that the page I opened.  It's my wallet code.  I have asked the GitHub team for advice regarding transactions or other matters but there has been no response. I understand some English but if I press copy I think it's mine but  I've never taken it anywhere. Everything is still there. As for tokens, I have no knowledge about them at all. As for stocks, I don't have any knowledge, so I did it without them.  I never intended to use it as my own. I just learned on YouTube that I used etherscan lately because I hadn't verified my identity and just came to read about its use later.  Because I saw a lot of rules and usage, and I couldn't even read English well, I skipped what I had to do and was just careful. I didn't think of taking anything as my own.  But if you do it unintentionally and don't understand the language and have no knowledge about crypto at all, I'm completely innocent because I didn't do anything wrong, but I may have misunderstood and not read the language well enough.  So I did the wrong thing unintentionally.

**Comment by AigaD** [comment] 2024-03-25 07:10
Tested from: https://preview.portalbridge.com/b05f4e9322/
Account creating shows as failed, reason `TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds.`, but after refreshing the page and entering the same values message to create associated account is no longer shown.

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/7d13ace7-09b2-4662-8407-61b9aa2ec605

<img width="1361" alt="Screenshot 2024-03-25 at 09 07 21" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4f2d3c03-5009-481b-8e1a-212fc2da2ffe">

**Comment by AigaD** [comment] 2024-03-27 08:35
Tested from: https://portalbridge.com/
User is able to create associated account for transaction to Solana.
Issue no longer reproduced, if issue will reappear ticket will be re-opened.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/369b3cca-b07c-44e0-a6a1-352063f66890

**Comment by AigaD** [comment] 2024-04-02 09:22
Re-opening the ticket.
Tested from: https://preview.portalbridge.com/8228d00809/#
Associated token account creation failed, reason `TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds.`
Linking to ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1689

Attachment:
<img width="1328" alt="Screenshot 2024-04-02 at 12 20 40" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/38f0ffe2-c311-4e65-ac43-21a426a44b31">

**Comment by AigaD** [comment] 2024-05-23 08:17
Tested from: https://deploy-preview-2113--wormhole-connect-mainnet.netlify.app/#
Creating account failed `TransactionExpiredTimeoutError: Transaction was not confirmed in 60.00 seconds.` for transaction DAI from Base (Metamask) to Solana (Bitget)
Attachment:

<img width="1252" alt="Screenshot 2024-05-23 at 11 16 04" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/285a4264-28d7-4f7a-9dc6-dee0fd64a16c">

**Comment by tsadovska** [comment] 2024-06-07 14:11
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet]:
* WGLMR transfer from Moonbeam (MetaMask) to Solana (Phantom): [Moonscan](https://moonscan.io/tx/0xf0af9eec2c8a00f2d774d20d565353064de7e779df4beaeccf09d0e6aaf4bfc0), [Solana Explorer](https://explorer.solana.com/tx/5HQNRSEfcPW6KuXD5kBBEwZRgorgvNJKhimAKMouj2v6nrHVypH44cLwHakh9RcsgMtV1Lr6YgoaLeQagKyP5uMk)
* USDT transfer from Osmosis (Leap) to Solana (Phantom): [MintScan](https://www.mintscan.io/osmosis/transactions/C0D8D775220CDE51DDCA6F789B4C64313C2605AC663ECD4266A61B7422BC46A8), [Solana explorer](https://explorer.solana.com/tx/2RHvQgqqKrQNE6Xx3hTsjbdVmA9wBeFASWqYSYKFJ9xFz6EXDaiN2ZrHBDSnmUBjRP9bgVqzYYV61bnThGsNW2qs)
* USDC transfer from Evmos (Leap) to Solana (Phantom): [MintScan](https://www.mintscan.io/evmos/tx/0528FE98842482BDB9135E610407F374B073D4B2E970C2816F10C16497AD9BB4), [Solana Explorer](https://explorer.solana.com/tx/31V4iBNrKdt3fSkPYs5GtFQmdbvkJHHddVr1JNJZoy9RdWgMtLYrCg9EioJfcoV18oGAXtGZoGuWfb4wr8BPucvQ)
* WSOL transfer from Injective (Leap) to Solana (Phantom): [Injective Explorer](https://explorer.injective.network/transaction/BBEFB00E338C464B09B76C578BB92A38009E628FB90E1B10CC98ACE666544197/), [Solana Explorer](https://explorer.solana.com/tx/2QyyymFkfFo9Z7jtpe3MitpVL9uSzJG8GsfNJL4v3jJMxprnihesioqKW6SWrXTXSbnTWbb65egeLvbqMcayEQke)
* USDC transfer from Polygon (MetaMask) to Solana (Phantom): [PolygonScan](https://polygonscan.com/tx/0xbab8093290b8fbf5318d5fd3512c7cd46f1ebdc238a9408f7a7149afca4db300), [Solana Explorer](https://explorer.solana.com/tx/4huTb7J3eR34HXbZpsfSHndoxbGTUJiWJVZjn18LLiWcdSRhwuKeGendZ2MYMnynkjzmYY4s6g46pUVXthUsCf2y)
* BNB from BSC (MetaMask) to Solana (Phantom): [BscScan](https://bscscan.com/tx/0x2f56eec6e115b5692a6ce6349306059938d8d49d46f5c038d4ade840f78f029f), [Solana Explorer](https://explorer.solana.com/tx/gbEwVnp44NYuAUXi3BbwCJnWd4ZmEHgWT3hGoM5TSr2qny6iBnTdpsJPNBUPXXEQqrRzgpK49Gt7wCAdY9tLffm)
* KLAY transfer from Klaytn (MetaMask) to Solana (Phantom): [Klaytn](https://klaytnscope.com/tx/0xf4863334845772740900c717d29997823cd3d8e20677c102d3296dc6000997da), [Solana Explorer](https://explorer.solana.com/tx/3RmScS7EWhF3U3CVLAG5Zns6ToXvDsmqVqxQQedeeSvfCcT7EF9fMc4TFGJDHPdfWYq3BtXmcj4Gm1LcPtefLQ3X)
* DAI transfer from Base (MetaMask) to Solana (Phantom): [BaseScan](https://basescan.org/tx/0xc75796a0fa3a9917d7fa454a89da86242c11e2fdd9ec49a36d489f32099d536e), [Solana Explorer](https://explorer.solana.com/tx/wghUWw7NmAiq6crVPJbJJZN54cSZxYAyXcPEgzUkHT3VynPoXN1cmnc7XD7dmyNR8YtsiaGnW5wGMBqbj4ELETc)

Ticket is closed.

**Closed as completed by tsadovska** 2024-06-07 14:11 UTC
Labels: p1, solana
