### ISSUE TITLE
[QA] WETH token is displayed as "Unknown" in Mintscan when receiving asset in Osmosis

### ISSUE THREAD

**Issue by mliu-xlabs** [wormhole-foundation/wormhole-connect#1295] opened 2023-12-04 21:18 UTC
**Is there an existing issue for this?**
 I have searched the existing issues

**Current Behavior**
WETH token is displayed as "Unknown" in Mintscan when receiving asset in Osmosis.

Send from tx: [Etherscan](https://etherscan.io/tx/0x4d040166ac741cba24e69aa8eb7afd4cac504ddbb7cbf473541f5efa14863e8d)
Send to tx: [Mintscan](https://www.mintscan.io/osmosis/transactions/2D0FE97CDAE6A843AEDC2108EB7EA5530D310BB9CDCE8C76D6C9932BE31850E9)

Transaction history on Osmosis (Account osmo167mxuwxeqs0cg6kf7s92l7uxrkhzzeky5s0f4t): [Leap wallet transaction history](https://www.mintscan.io/osmosis/accounts/osmo167mxuwxeqs0cg6kf7s92l7uxrkhzzeky5s0f4t/transactions)

**Expected Behavior**
WETH token is displayed correctly in Mintscan.

**Steps To Reproduce**
Send ETH (in my case 0.00012) from Ethereum (Metamask) to Osmosis (Leap)
Wait until transaction in completed (link to Mitscan is not displayed on Redeen screen https://github.com/XLabs/portal-bridge-ui/issues/360)
Open [www.mintscan.io](http://www.mintscan.io/)
Search for transaction by wallet address

**Environment**
- **OS:** macOS Monterey Version 12.6.7
- **Wallets:**
  Metamask 0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012
  Leap osmo167mxuwxeqs0cg6kf7s92l7uxrkhzzeky5s0f4t 
- **Browser:** Google Chrome Version 116.0.5845.110 (Official Build) (x86_64)
- **Build:** https://preview.portal-bridge-ui.pages.dev/96d72fd6f0/cosmos/
Anything else?
Attachments:

![Image](https://github.com/wormhole-foundation/wormhole-connect/assets/130170527/1d3dbee4-4769-4490-9501-c97f6b2a68f0)

![Image](https://github.com/wormhole-foundation/wormhole-connect/assets/130170527/53417f37-2114-4c66-9b2c-a085eefbd03e)

Migrated from: https://github.com/XLabs/portal-bridge-ui/issues/365

**Comment by tsadovska** [comment] 2024-08-16 12:13
Issue is still reproducible. WETH token is displayed as "Unknown" on Mintscan.

Checked on https://portalbridge.com/. 
Scenario: 0.0000001 transfer from Ethereum (MetaMask) to Osmosis (Leap). 
* Send from tx: [Etherscan](https://etherscan.io/tx/0xc66d79e1e94639c66c734a68d0e9a7ebb4d5e6c516e370618888cd7a592b95e6)
* Send to tx: [Mintscan](https://www.mintscan.io/osmosis/transactions/3650DBF09D8CD5CA832972D6DFE50C70E144972C77AF921D943CEB16415A37B8)


Information from Mintscan:
<google-sheets-html-origin>
index | type | from | to | txhash | amount | token | denom | timestamp
-- | -- | -- | -- | -- | -- | -- | -- | --
1 | IBCReceive | wormhole14ejqjyq8um4p3xfqj74yld5waqljf88fz25yxnma0cngspxe3les00fpjx | osmo167mxuwxeqs0cg6kf7s92l7uxrkhzzeky5s0f4t | 3650DBF09D8CD5CA832972D6DFE50C70E144972C77AF921D943CEB16415A37B8 | 0.00001 | Unknown | factory/wormhole14ejqjyq8um4p3xfqj74yld5waqljf88fz25yxnma0cngspxe3les00fpjx/5BWqpR48Lubd55szM5i62zK7TFkddckhbT48yy6mNbDp | 2024-08-16 12:00:51
2 | IBCReceive | wormhole14ejqjyq8um4p3xfqj74yld5waqljf88fz25yxnma0cngspxe3les00fpjx | osmo167mxuwxeqs0cg6kf7s92l7uxrkhzzeky5s0f4t | 3650DBF09D8CD5CA832972D6DFE50C70E144972C77AF921D943CEB16415A37B8 | 0.00001 | Unknown | factory/wormhole14ejqjyq8um4p3xfqj74yld5waqljf88fz25yxnma0cngspxe3les00fpjx/5BWqpR48Lubd55szM5i62zK7TFkddckhbT48yy6mNbDp | 2024-08-16 12:00:51

**Comment by tsadovska** [comment] 2024-10-03 07:31
Closing the ticket, because Cosmos chains are no displayed on https://wormhole-connect-mainnet.netlify.app/ and https://portalbridge.com/.

**Closed as not planned by tsadovska** 2024-10-03 07:31 UTC
Labels: osmosis, explorer
