### ISSUE TITLE
[QA] Transaction switched to incorrect Network when Claiming asset

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1634] opened 2024-02-12 11:17 UTC
Preconditions:
Metamask wallet connected though WalletConnect mobe Metamask app
Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85
iPhone 14, iOS 16.0

Tested from: https://wormhole-connect.netlify.app/#

Steps: 
1. Select Menu and Resume transaction
2. Paste in transaction hash for transaction from [Mumbai](https://mumbai.polygonscan.com/tx/0x8745ac95fb1030ac901f9b1d81eb78158b1d1a7bc4d46914aba98e11d467d7c7) 0x8745ac95fb1030ac901f9b1d81eb78158b1d1a7bc4d46914aba98e11d467d7c7 to Fuji
3. Click Search
4. Click Claim When possible
5. Observe if correct Network is switched on the mobile device Metamask app

Actual result: Network showed as switched to Polygon Mumbai

Expected result: Network should have switched to Fuji Network when Claim was clicked

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2ea6b90b-a0df-43fa-b612-b309e1ac507c

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8ee18d2f-1895-4f9e-9a6a-1af9df97f937

**Comment by tsadovska** [comment] 2024-08-26 15:37
* Issue is not reproducible on https://wormhole-connect.netlify.app/ when sending 0.000123 CELO from Alfajores (MetaMask) to Fuji (MetaMask).
* Cannot reproduce the [original scenario,](https://github.com/wormhole-foundation/wormhole-connect/issues/1634#issue-2129918374) because Mumbai network is deprecated. 

Closing the ticket.

**Closed as completed by tsadovska** 2024-08-26 15:37 UTC
Labels: p2
