### ISSUE TITLE
Investigate gas limits

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#826] opened 2023-08-16 18:12 UTC
Surfaced in https://github.com/wormhole-foundation/wormhole-connect/issues/228

```
Send.tsx:106 Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x0a370E7c5F7F944d451B48bc151a7BEC454bc185","gasLimit":{"type":"BigNumber","hex":"0x03d090"},"to":"0xF890982f9310df57d00f659cf4fd87e65adEd8d7","value":{"type":"BigNumber","hex":"0x2aa1efb94e0000"},"data":"0x9981509f00000000000000000000000000000000000000000000000000000000000000019c6746b429022c874c3679e8147dda94890c313a1a74325f976863de7e8e9cac000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c3110100","accessList":null}, error={"code":-32000,"message":"err: insufficient funds for gas * price + value: address 0x0a370E7c5F7F944d451B48bc151a7BEC454bc185 have 0 want 12000000000000000 (supplied gas 250000)"}, code=CALL_EXCEPTION, version=providers/5.7.2)
```

TDLR: `error={"code":-32000,"message":"err: insufficient funds for gas * price + value: address 0x0a370E7c5F7F944d451B48bc151a7BEC454bc185 have 0 want 12000000000000000 (supplied gas 250000)"}`

Review gas limits for all chains to see if we can eliminate this kind of error

**Comment by tsadovska** [comment] 2024-02-29 16:07
Closing the ticket because issue was not reproducible for more than 6 month.

**Closed as completed by tsadovska** 2024-02-29 16:07 UTC
Labels: bug, p1
