### ISSUE TITLE
[QA]"This transaction requires 24 hours to complete" message is shown when all required fields are not met

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1617] opened 2024-02-08 07:56 UTC
Preconditions:
Wallet is not connected at sending from section
Metamask wallet connected at sending To section

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect.netlify.app/# 

Steps:
1. Select Solana Network at sending From section
2. Connect Klaytn at sending To section
3. Select SOL asset
4. Write o.1 in amount section
5. Observe

Actual result: Message "This transaction requires 24 hours to complete" is shown when al the fields are not completed yet for the transaction, by clicking on Continue user is taken to the bottom of the page where Approve button should be shown if all the requirements would be met

Expected result: Message is not shown until user clicks on Approve button after completing all required fields

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/183770a6-08f6-442e-b99b-78cbaeed6b51

**Comment by agodlevska** [comment] 2024-07-24 08:55
The issue is no longer reproducible on https://wormhole-connect.netlify.app/ and https://wormhole-connect-mainnet.netlify.app/. 
Pop-up "This transaction will take up to 24 hours to complete" is not shown when all required fields are not met.
Closing the ticket.

Attachments:

https://github.com/user-attachments/assets/6a326f40-c127-473c-9f18-695bc33fc879

**Closed as completed by agodlevska** 2024-07-24 08:55 UTC
Labels: p2
