### ISSUE TITLE
[QA] [Mainnet] PolygonScan link leads to invalid transaction hash result

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2086] opened 2024-05-15 14:00 UTC
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.208 (Official Build) (arm64).

Steps:
1. Prepare to send 0.0004 WETH (Avalanche) from Avalanche (MetaMask) to Polygon (MetaMask)
2. Click "Approve and proceed with transaction" button
3. Click on "Polygonscan" link in "Send to" section

Actual result: Page is opened https://polygonscan.com/tx/07b35e508ffa842866a4e19d3ce004070216a3622c44e2a2169801651b67213b. Error: "Oops! An invalid Txn hash has been entered: 07b35e508ffa842866a4e19d3ce004070216a3622c44e2a2169801651b67213b"

Expected result: Correct link is opened https://polygonscan.com/tx/0x07b35e508ffa842866a4e19d3ce004070216a3622c44e2a2169801651b67213b

## Notes/ Attachments
Similar issues: https://github.com/wormhole-foundation/wormhole-connect/issues/1919, https://github.com/wormhole-foundation/wormhole-connect/issues/1909, https://github.com/wormhole-foundation/wormhole-connect/issues/2057.

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/96d75b7c-e360-4387-8d70-acba26022f25)

**Comment by tsadovska** [comment] 2024-05-30 10:13
Reproducible on https://deploy-preview-2143--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0003 wstETH from Ethereum (MetaMask) to Polygon (MetaMask). 

* Send from tx: [Etherscan](https://etherscan.io/tx/0x3baa0e8d8eff7ac7efcd8e4559bc29ab61ca74a9c5d0d61b628e3201e2984200)
* Send to tx: [Polygonscan](https://polygonscan.com/tx/c8faa4c08d05ba53ccee041e26de1a2abe714db53a0303b001ed88a402074e09) instead of [Polygonscan](https://polygonscan.com/tx/0xc8faa4c08d05ba53ccee041e26de1a2abe714db53a0303b001ed88a402074e09)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x3baa0e8d8eff7ac7efcd8e4559bc29ab61ca74a9c5d0d61b628e3201e2984200)

**Comment by agodlevska** [comment] 2024-06-20 08:56
Reproducible on https://preview.portalbridge.com/933197c94d/ when sending 0.00001 wstETH from Base (Rabby) to Polygon (Rabby).

Send from tx: [Base](https://basescan.org/tx/0x448442e9d617046ee27b8681b510d7c2cfa1b552e4e48e34eda82b81eb4ee42f)
Send to tx: [Polygonscan](https://polygonscan.com/tx/c8faa4c08d05ba53ccee041e26de1a2abe714db53a0303b001ed88a402074e09) instead of [Polygonscan](https://polygonscan.com/tx/0xc8faa4c08d05ba53ccee041e26de1a2abe714db53a0303b001ed88a402074e09)
Link to [Wormholescan](https://wormholescan.io/#/tx/0x448442e9d617046ee27b8681b510d7c2cfa1b552e4e48e34eda82b81eb4ee42f)

**Comment by agodlevska** [comment] 2024-07-18 08:55
Reproducible on https://preview.portalbridge.com/3365c86aff/ when sending 1 USDT from Arbitrum (MetaMask) to Polygon (MetaMask).

- Send from tx: [Arbitrum](https://arbiscan.io/tx/0xf6c7401ec159d67239232cc4f0ff795b53986304d363e8fe10ae9d53c35e5c05)
- Send to tx: [Polygonscan](https://polygonscan.com/tx/af71b889b7ac110d260b91663f52973c4ecb8e7cae1f9916dfec63bfaa7efd84) instead of [Polygonscan](https://polygonscan.com/tx/0xaf71b889b7ac110d260b91663f52973c4ecb8e7cae1f9916dfec63bfaa7efd84)
- Link to [Wormholescan](https://wormholescan.io/#/tx/0xf6c7401ec159d67239232cc4f0ff795b53986304d363e8fe10ae9d53c35e5c05)

**Comment by tsadovska** [comment] 2024-07-18 08:59
Reproducible on https://preview.portalbridge.com/3365c86aff/ [Mainnet] when sending 0.1 USDT from Base (MetaMask) to Polygon (MetaMask). 
* Send from tx: [Base](https://basescan.org/tx/0x3829a7f7898870147e41f69558aa218dcd7da55d157294d62191d30d2673cf25)
* Send to tx: [invallid link](https://polygonscan.com/tx/551475b4d7d0d01eccd58500247b3b814197b180521bf2e8f560f3bfa7afa0ad) is opened instead of [correct link](https://polygonscan.com/tx/0x551475b4d7d0d01eccd58500247b3b814197b180521bf2e8f560f3bfa7afa0ad) to Polygonscan
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x3829a7f7898870147e41f69558aa218dcd7da55d157294d62191d30d2673cf25)

**Comment by agodlevska** [comment] 2024-08-15 07:13
Reproducible on https://preview.portalbridge.com/321a610744/ when sending 0.00001 ETH from Optimism (MetaMask) to Polygon (MetaMask).

- Send from tx: [Optimism](https://optimistic.etherscan.io/tx/0x83c7b0fdb1cbd55ac8a76b329a0921243512b87381ed26e3c57f5807388a2821)
- Send to tx: [Polygonscan](https://polygonscan.com/tx/4f0fa9c290ee82fd00ade427333367e0de61fc9bb7a6228c80504a8b27a866ae) instead of [Polygonscan](https://polygonscan.com/tx/0x4f0fa9c290ee82fd00ade427333367e0de61fc9bb7a6228c80504a8b27a866ae)
- Link to [Wormholescan](https://wormholescan.io/#/tx/0x83c7b0fdb1cbd55ac8a76b329a0921243512b87381ed26e3c57f5807388a2821)

**Comment by agodlevska** [comment] 2024-09-24 08:09
The issue is no longer relevant after the redesign, link on destination chain is no longer displayed.
Closing the ticket.

**Closed as not planned by agodlevska** 2024-09-24 08:09 UTC
Labels: p2, explorer
