### ISSUE TITLE
[QA] [Mainnet] Arbitrum explorer link leads to invalid transaction hash result 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1909] opened 2024-04-10 15:37 UTC
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Prepare to send 0.001 wstETH (Optimism) from Optimism (MetaMask) to Arbitrum (MetaMask)
2. Click "Approve and proceed with transaction" button
3. Click on "Arbitrum Explorer" link

Actual result: Arbitrum explorer link opens result "Oops! An invalid Txn hash has been entered: 69235afe48783af90f4d31c50efdc880da86d1993fc86acbb0557936de942a2b". Link https://arbiscan.io/tx/69235afe48783af90f4d31c50efdc880da86d1993fc86acbb0557936de942a2b 

Correct link is https://arbiscan.io/tx/0x69235afe48783af90f4d31c50efdc880da86d1993fc86acbb0557936de942a2b

Error:
```
 Error: invalid hash (argument="value", value="69235afe48783af90f4d31c50efdc880da86d1993fc86acbb0557936de942a2b", code=INVALID_ARGUMENT, version=providers/5.7.2)
    at Logger.makeError (/assets/main-BIApWWvg.js:166:46729)
    at Logger.throwError (/assets/main-BIApWWvg.js:166:46862)
    at Logger.throwArgumentError (/assets/main-BIApWWvg.js:166:46923)
    at Formatter.hex (/assets/main-BIApWWvg.js:172:74447)
    at Formatter.hash (/assets/main-BIApWWvg.js:172:75118)
    at StaticJsonRpcProvider.<anonymous> (/assets/main-BIApWWvg.js:172:108186)
    at Generator.next (<anonymous>)
    at Hn (/assets/main-BIApWWvg.js:172:79192)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/18a82bba-235a-4c07-a56e-26717fa55cb2)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/2b10d01e-7935-4bed-aec4-0356c136210c

## What is the expected/desired behavior
Link to "Arbitrum explorer" opens transaction details page.

**Comment by tsadovska** [comment] 2024-04-30 14:52
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ when sending 0.0003 wstETH (Optimism) from Optimism (MetaMask) to Arbitrum (MetaMask).

Arbitrum explorer link opens result "Oops! An invalid Txn hash has been entered: 73c013ff53226ea3436ad9f56799ca00b845653f2bf6f08bd5a4d349fe73d286" https://arbiscan.io/tx/73c013ff53226ea3436ad9f56799ca00b845653f2bf6f08bd5a4d349fe73d286 instead of https://arbiscan.io/tx/0x73c013ff53226ea3436ad9f56799ca00b845653f2bf6f08bd5a4d349fe73d286. 

Send from tx: https://optimistic.etherscan.io/tx/0x2164fd439409672f8dc37fa09199612fc1730b03fa2c57b9b351c16c039e8bb6
Link to Wormholescan: https://wormholescan.io/#/tx/0x2164fd439409672f8dc37fa09199612fc1730b03fa2c57b9b351c16c039e8bb6

**Comment by kev1n-peters** [comment] 2024-04-30 15:11
Think this happens when the TX hash is fetched from wormholescan and is not normalized with the `0x` prefix

**Comment by tsadovska** [comment] 2024-05-30 08:28
Reproducible on https://deploy-preview-2143--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending 0.0015 ETH from Ethereum (MetaMask) to Arbitrum (MetaMask). 
* Send from tx: [Etherscan](https://etherscan.io/tx/0xfed1421c94bb9c3038f34371b30cf653bf58b2dbbae46376f18717227d94b7fd)
* Send to tx: [Arbitrum Explorer](https://arbiscan.io/tx/8442e13a917f2516d2a102de511b2afcfda427f43e760ea7079d19bbfbd17496) instead of [Arbitrum Explorer](https://arbiscan.io/tx/0x8442e13a917f2516d2a102de511b2afcfda427f43e760ea7079d19bbfbd17496)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0xfed1421c94bb9c3038f34371b30cf653bf58b2dbbae46376f18717227d94b7fd)

**Comment by tsadovska** [comment] 2024-06-14 18:00
Reproducible on https://preview.portalbridge.com/2c6f665417/ [Mainnet] when sending 0.0001 WETH (Polygon) from Polygon (MetaMask) to Arbitrum (MetaMask). 
* Send from tx: [Polygonscan](https://polygonscan.com/tx/0xb5d4384a1508fc6519991f4430cbadee196f35e3e736a91cf04255d77c070856)
* Send to tx: [Arbitrum Explorer](https://arbiscan.io/tx/3d4666d79a28e2ccb6ec2cb3f0886ca1ea278420d05f3d7d5e6974852e608f8d) instead of [Arbitrum Explorer](https://arbiscan.io/tx/0x3d4666d79a28e2ccb6ec2cb3f0886ca1ea278420d05f3d7d5e6974852e608f8d)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0xb5d4384a1508fc6519991f4430cbadee196f35e3e736a91cf04255d77c070856)

**Comment by agodlevska** [comment] 2024-06-26 08:41
Reproducible on https://preview.portalbridge.com/8b6491733c/ [Mainnet] when sending 0.001 ETH (Ethereum) from Ethereum (MetaMask) to Arbitrum (MetaMask).

- Send from tx: [Ethereum](https://etherscan.io/tx/0x5214cdb634bdd2162dfc574bef7f57669f232b329dcc28ef4c4c30bc68975e9a)
- Send to tx: [Arbitrum](https://arbiscan.io/tx/f069103e88d2659d7d47dd8a88ebf1ab6dfdd96c90970967b048faa4c2391fd2) instead of [Arbitrum](https://arbiscan.io/tx/0xf069103e88d2659d7d47dd8a88ebf1ab6dfdd96c90970967b048faa4c2391fd2)
- Link to [Wormholescan](https://wormholescan.io/#/tx/0x5214cdb634bdd2162dfc574bef7f57669f232b329dcc28ef4c4c30bc68975e9a)

**Comment by agodlevska** [comment] 2024-07-18 08:50
Reproducible on https://preview.portalbridge.com/3365c86aff/ when sending 1 USDT from Optimism (MetaMask) to Arbitrum (MetaMask).

- Send from tx: [Optimism](https://optimistic.etherscan.io/tx/0x04b3d12c9bfda3184052974c5b9f217acf2ac13a60d544ce76a59363e9774206)
- Send to tx: [Arbitrum](https://arbiscan.io/tx/b2b9c615991432439dbeaed89bf7e5bec4af430b20f7454a600e0516b34a9197) instead of [Arbitrum](https://arbiscan.io/tx/0xb2b9c615991432439dbeaed89bf7e5bec4af430b20f7454a600e0516b34a9197)
- Link to [Wormholescan](https://wormholescan.io/#/tx/0x04b3d12c9bfda3184052974c5b9f217acf2ac13a60d544ce76a59363e9774206)

**Comment by agodlevska** [comment] 2024-08-27 09:37
Reproducible on https://preview.portalbridge.com/b3b7091778/ when sending 0.0001 ETH from Ethereum (MetaMask) to Arbitrum (MetaMask).

- Send from tx: [Ethereum](https://etherscan.io/tx/0x43783bc7bc2dffae5358202f6401bbb524e7530a0b8dc29cdd25ff834b90eb57)
- Send to tx: [Arbitrum](https://arbiscan.io/tx/812e3d0ab977e3c583c757866c9e91e34bc3c0f9c93c440418548970294367b1) instead of [Arbitrum](https://arbiscan.io/tx/0x812e3d0ab977e3c583c757866c9e91e34bc3c0f9c93c440418548970294367b1)
- Link to [Wormholescan](https://wormholescan.io/#/tx/0x43783bc7bc2dffae5358202f6401bbb524e7530a0b8dc29cdd25ff834b90eb57)

**Comment by agodlevska** [comment] 2024-09-24 08:38
The issue is no longer relevant after the redesign, link on destination chain is no longer displayed.
Closing the ticket.

**Closed as not planned by agodlevska** 2024-09-24 08:38 UTC
Labels: p2, explorer
