### ISSUE TITLE
[QA] [Mainnet] SUI -> Osmosis transaction fails

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#856] opened 2023-08-25 07:33 UTC
Preconditions:
1. Sui Wallet connected at sending From section
2. Keplr Wallet connected at sending To section
3. Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://feat-cosmos-gateways-mainnet--wormhole-connect.netlify.app/

Steps:
1. Prepare to send 0.1 SUI from Sui to Osmosis
2. Click Approve and proceed with transaction
3. Observe

Actual result: Transaction fails, error in console indicates `Sui transfer with payload not implemented`

Expected result: Transaction is started

Attachment:
<img width="1326" alt="Screenshot 2023-08-25 at 10 25 59" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4ac24991-1b99-40b9-a6c6-4cea06234517">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/55e08f09-a7fe-46df-aab9-dd808b742677

**Comment by tsadovska** [comment] 2023-08-25 12:15
Issue is reproducible on https://feat-cosmos-gateways--wormhole-connect.netlify.app/ [Testnet] when sending 0.5 SUI from Sui (Sui wallet) to Osmosis (Leap). 

Error is displayed in Console after clicking on "Approve and proceed with transaction" button:
```
Error: Sui transfer with payload not implemented
    at main.bbca42eb.js:37:18715
    at Generator.next (<anonymous>)
    at main.bbca42eb.js:37:9217
    at new Promise (<anonymous>)
    at aI (main.bbca42eb.js:37:8962)
    at vI (main.bbca42eb.js:37:18662)
    at b.innerSend (main.bbca42eb.js:37:18142748)
    at async Lf.toCosmos (main.bbca42eb.js:110:155390)
    at async xb.send (main.bbca42eb.js:110:201528)
    at async Object.onClick (main.bbca42eb.js:137:24093)
```

**Comment by tonyjin** [comment] 2023-08-29 18:29
~~This appears to be resolved on testnet using the testnet build you posted above. Assigning back to you to close @AigaD.~~

Nvm, APT transfer appeared to be successful in UI but don't see in receiving wallet. May be a testnet relayer issue.

**Comment by tonyjin** [comment] 2023-08-30 15:16
Going to close this issue since the title is for mainnet and is categorized as P0. Want to focus on testnet heading into scheduled launch tomorrow.

**Closed as completed by tonyjin** 2023-08-30 15:16 UTC
Labels: p0
