### ISSUE TITLE
[QA] Pop-up "This transaction will take up to 24 hours to complete" is shown when route is not available 

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1557] opened 2024-01-26 11:27 UTC
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome. 

1. Select "Polygon" network as source chain and connect "Metamask" wallet in "From" section
2. Select "Avalanche" network as destination chain and connect "Metamask" wallet in "To" section
3. Select WETH (Base) asset
4. Enter amount 0.00001

Actual result: Pop-up "This transaction will take up to 24 hours to complete" is shown when route is not available (ticket: https://github.com/wormhole-foundation/wormhole-connect/issues/1487).

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/bbbe1413-ced0-4109-aded-fa81401a523b

## What is the expected/desired behavior
Pop-up "This transaction will take up to 24 hours to complete" is not shown.

**Comment by agodlevska** [comment] 2024-07-24 08:37
The issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/. 
Pop-up "This transaction will take up to 24 hours to complete" is not shown when route is not available.
Closing the ticket.

Attachments: 

https://github.com/user-attachments/assets/1ca07781-8dd5-4969-8e47-89ad1c537b0c


<img width="692" alt="Screenshot 2024-07-24 at 11 40 45" src="https://github.com/user-attachments/assets/13f2b615-054e-4282-aff5-48e131f60b2e">

**Closed as completed** 2024-07-24 08:42 UTC
Labels: p2
