### ISSUE TITLE
[QA] It seems that Keplr wallet was connected, when connection to Leap wallet was made

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1744] opened 2024-03-04 08:59 UTC
Preconditions:
Keplr wallet extension is disabled 
Leap wallet extension is enabled

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from:
https://wormhole-connect-mainnet.netlify.app/#

Steps:
1. Connect Osmosis network
2. Click on Connect Wallet
3. Observe the available wallets (Keplr wallet showing as installed reported here https://github.com/wormhole-foundation/wormhole-connect/issues/1577 )
4. Click on Keplr
5. Observe

Actual result: It seems that user has connected to Keplr wallet (Keplr wallet logo is shown), but actually Leap wallet was connected

Expected result: If Keplr wallet extension is not installed it should not shown as available and Leap wallet should not be connected when Keplr is selected

Comments: Linking to https://github.com/wormhole-foundation/wormhole-connect/issues/1577

Attachment:

![Screenshot 2024-03-04 at 10 52 47](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1dd9840e-40a3-4a05-881c-0432d2d63b80)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/41c3a312-a0e9-4bdd-b815-0f312a785011

**Comment by AigaD** [comment] 2024-03-28 08:39
Tested from: https://portalbridge.com/
Keplr wallet extension has been disabled, but it still shows as available in the wallet list. When creating connection Leap wallet is connected instead of Keplr, but it indicates as Keplr wallet had been connected.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e31eb7ce-9013-4511-b678-449a5e62a54d

**Comment by agodlevska** [comment] 2024-09-10 08:59
Tested from: https://portalbridge.com/. 
Keplr wallet extension has been disabled, but it still shows as available in the wallet list. Also, the Keplr wallet can be connected. 

Attachment:

https://github.com/user-attachments/assets/254e629a-0339-4551-ab8c-059403d3f748

**Comment by agodlevska** [comment] 2024-10-03 12:19
The issue is no longer relevant after the redesign, Cosmos chains are not available on https://wormhole-connect-mainnet.netlify.app/ and https://portalbridge.com/.
Closing the ticket.

**Closed as not planned by agodlevska** 2024-10-03 12:19 UTC
Labels: p2
