### ISSUE TITLE
[QA] Balances for several networks are not loading - Error 429 (Too many requests)

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2359] opened 2024-08-12 10:25 UTC
## Describe the current behavior in detail
Builds:

- https://wormhole-connect-mainnet.netlify.app/ [Mainnet] - reproducible
- https://portalbridge.com/ [Mainnet] - Tested OK

Steps:
1. Open [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D)
2. Select Polygon in "From" section, MetaMask wallet is automatically connected
3. Check token balances in "Select a token" section

Actual result: Balance is not loaded.
Expected result: Balance is loaded.

Checked with macOS Sonoma 14.5 and Google Chrome Version 127.0.6533.100 (Official Build) (arm64).

## Notes/ Attachments

![image](https://github.com/user-attachments/assets/b74abf3a-dca9-40a6-a96b-7e8144789cdd)

**Comment by tsadovska** [comment] 2024-08-12 12:34
Issue is also reproducible on Ethereum, Avalanche, Fantom, Moonbeam.

**Comment by tsadovska** [comment] 2024-08-19 06:55
Token balances on the Ethereum, Avalanche, and Moonbeam networks are successfully loading. Token balances are still not loading on the Fantom network (Ticket https://github.com/wormhole-foundation/wormhole-connect/issues/2400).

Ticket is closed.

**Comment by agodlevska** [comment] 2024-08-20 08:56
Reopening the issue.
Issue is reproducible with Polygon, BSC and Ethereum networks. 

We have created a document to track the progress of network balance loading. You can find the document [here](https://docs.google.com/spreadsheets/d/1NQJDI9hmEeS-K8eKWZLIEbAFJ-IvMfU4eYEWNs6MOl8/edit?gid=0#gid=0).

**Comment by agodlevska** [comment] 2024-08-23 07:02
Issue is still reproducible on [wormhole-connect-testnet](https://wormhole-connect.netlify.app/?config=N4KABGCmB2BuBcYDkAXSBnF1IqQGnDAFd1IAlSAEwwEsBzaRFAJyMhAF8Qg%3D) and [wormhole-connect-mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D), more info [here](https://docs.google.com/spreadsheets/d/1NQJDI9hmEeS-K8eKWZLIEbAFJ-IvMfU4eYEWNs6MOl8/edit?gid=0#gid=0). 

Also, wrapped tokens balance is not loading for Scroll, Blast, X Layer (mainnet) and for Sepolia, Arbitrum Sepolia, Base Sepolia, Optimism Sepolia (testnet).

**Comment by emreboga** [comment] 2024-08-27 03:38
This is an issue related to the RPC endpoint not working well with the netlify deployment and returning 429 (Too many requests). I think we can update the endpoints for Netlify.

**Comment by tsadovska** [comment] 2024-08-27 15:37
Linked issue: https://github.com/wormhole-foundation/wormhole-connect/issues/2443 Balance is not loading on BSC - error "Batch size too large"

**Comment by tsadovska** [comment] 2024-08-27 16:12
Balances are now successfully loading on https://wormhole-connect-mainnet.netlify.app/ and https://wormhole-connect.netlify.app/. 

Closing the ticket.

**Comment by tsadovska** [comment] 2024-08-27 16:35
Reopening the ticket. It was reproducible with following scenario:

1. Prepare to send 5 FTM from Fantom (MetaMask) to Avalanche (MetaMask)
2. Select "Automatic Bridge" option
3. Click on "Review" button
4. Change slider position

**Comment by tsadovska** [comment] 2024-09-03 06:03
Checked on https://wormhole-connect-mainnet.netlify.app/.

Balances are no longer loading on Ethereum, BSC, Polygon, Avalanche, Celo, Moonbeam, Optimism, Arbitrum, Klaytn, Scroll, Blast after following steps:
1. Opens https://wormhole-connect-mainnet.netlify.app/ on mobile
2. Prepare to send MATIC form Polygon (MetaMask) to Avalanche (MetaMask)
3. Enter amount, 40 
4. Change amount to 3 
5. Check if balances are loading on mobile or desktop for EVM chains

Actual result: Balances are not loading.

**Comment by agodlevska** [comment] 2024-09-09 08:09
Checked on https://wormhole-connect-mainnet.netlify.app/.

Balances are no longer loading on Arbitrum, Optimism, Fantom, Polygon, Avalanche, Celo, Moonbeam, Klaytn, Scroll, Blast. 

Attachment:
<img width="1440" alt="Screenshot 2024-09-09 at 11 06 24" src="https://github.com/user-attachments/assets/87607fd8-bdb8-4a28-ab66-2bcd63a30fc4">

**Comment by Wesleyleung** [comment] 2024-09-19 03:45
I believe this is resolved?

**Comment by agodlevska** [comment] 2024-09-19 12:47
Checked on https://wormhole-connect-mainnet.netlify.app/ and https://preview.portalbridge.com/b1f3c5115d/. 

Currently, the balance is loading for almost all networks except Klaytn and Aptos. Tickets related to these networks have been created (https://github.com/wormhole-foundation/wormhole-connect/issues/2604, https://github.com/XLabs/portal-bridge-ui/issues/1079). The only issue that seems incorrect is that when loading the balance on https://wormhole-connect-mainnet.netlify.app/, there are occasional console errors stating that the balance could not be loaded. However, the balance does load for these networks. If this is not considered a problem, we can close the ticket.

Attachments:
<img width="1439" alt="Screenshot 2024-09-19 at 15 37 34" src="https://github.com/user-attachments/assets/dce061ee-05ea-4bce-a4da-cdebba3f6faa">
<img width="1440" alt="Screenshot 2024-09-19 at 15 38 07" src="https://github.com/user-attachments/assets/8be5f75e-7a64-4487-86de-49abd8fff822">

**Comment by agodlevska** [comment] 2024-10-10 08:49
It seems the issue is no longer reproducible.
Closing the ticket.

**Closed as completed by agodlevska** 2024-10-10 08:49 UTC
Labels: p0, connect v2
