### ISSUE TITLE
[QA] [Mainnet]  Invalid Transaction digest at JsonRpcProvider for transaction from Sui Network

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1724] opened 2024-02-28 10:35 UTC
Preconditions:
Fewcha (Sui Mainnet) wallet connected at sending From section
Leap (Osmosis Mainnet) connected at sending To section
Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.184

Tested from:
https://wormhole-connect.netlify.app/ - Tested NOK
https://wormhole-connect-mainnet.netlify.app/# - Tested NOK

Steps:
Prepare to send 0.01 SUI from Sui to Osmosis
Click Approve and proceed with transaction
Observe

Actual result: Transaction is not moving forward, error in console `main.js:499 Error: Invalid Transaction digest at JsonRpcProvider.getTransactionBlock` but asset value is reduced from the wallet

Expected result: Transaction is moved to next screen and is completed

Attachment:
[Sui explorer](https://suiexplorer.com/txblock/FHsdHNGKBkiMXCaugSrJ2uhSUaTRR5kSWvMuykzhZAKo?network=testnet) taken from transaction activity in the wallet 

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4e4ecc11-c14b-42d9-8bc4-d58cd865e614

![Screenshot 2024-02-28 at 12 24 07](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/84aafa8f-4a5f-4fe2-875a-ef884e62dfd5)

**Comment by AigaD** [comment] 2024-03-21 10:34
Tested from: https://wormhole-connect-mainnet.netlify.app/
Transaction 0.001 SUI from Sui (Fewcha Move) to Osmosis (Leap) is not starting, `Error: Invalid Transaction digest`, but funds are removed from the wallet

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0216fc17-d0d3-4601-b5e2-3ec2805a6bd3

<img width="1285" alt="Screenshot 2024-03-21 at 12 27 02" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c6a2a4d8-7fdf-47de-87ed-b4d3ae59c20a">

**Comment by AigaD** [comment] 2024-03-28 08:46
Reproduced from: https://portalbridge.com/
Asset amount was taken from the wallet, but transaction did not start, `Error: Invalid Transaction digest`
0.01 SUI from Sui (Fewcha Move) to Osmosis (Leap).
[Sui explorer](https://suiscan.xyz/mainnet/tx/YE1dfsV6LK2sWfnwjcoHNTkVUiNisQjCD1XAeGkiS6n)
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/565e78bc-ddf7-4913-800d-a2aada7bdf35

**Comment by AigaD** [comment] 2024-04-08 12:49
Tested from: https://wormhole-connect.netlify.app/
Transaction SUI from Sui (Fewcha Move) to Klaytn is not starting, reason `Error: Invalid Transaction digest`
Attachment:
<img width="1288" alt="Screenshot 2024-04-08 at 15 47 09" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/887981fb-2bf9-455d-8f5d-3656d8378346">

**Comment by AigaD** [comment] 2024-04-15 09:53
Tested from: https://deploy-preview-1869--wormhole-connect-mainnet.netlify.app/#
Transaction 0.0001 WSOL from Sui (Fewcha Move) to Solana (Phantom) is not starting, console shows `Error: Invalid Transaction digest`
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/73097501-5288-4a3e-be96-bef2227320f3

**Comment by AigaD** [comment] 2024-05-21 07:10
Issue is still reproducible.
Tested from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJNzYZCxCLhGTcM%2BYpHcUBjNzWCwmuTEVmwAXxB2gA%3D%3D#)
When sending 0.01 SUI from Sui (Fewcha) to Osmosis (Leap) transaction is not moving forward, console shows `main-CVK0tZG3.js:527 Error: Invalid Transaction digest`

Attachment:

<img width="1281" alt="Screenshot 2024-05-21 at 10 10 19" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/89e38672-e17f-4f14-98e7-31f451470ca7">

**Comment by tsadovska** [comment] 2024-07-31 15:10
Reproducible on https://portalbridge.com/ [Mainnet] with the same scenario, when sending 0.001 SUI from Sui (Fewcha) to Osmosis (Leap). The TransactionID in the link is "undefined". 


![Screenshot 2024-07-31 at 18 09 20](https://github.com/user-attachments/assets/fc7a6130-97a1-46f4-99af-7218af42f915)

**Comment by tsadovska** [comment] 2024-08-22 11:32
Closing as duplicate of https://github.com/wormhole-foundation/wormhole-connect/issues/1054.

**Closed as not planned by tsadovska** 2024-08-22 11:32 UTC
Labels: p1
