### ISSUE TITLE
[QA] User can not connect to Phantom/Solflare wallet if Phantom/Solflare is already connected in either Send from or Send to section

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#145] opened 2023-03-03 10:35 UTC
Preconditions:
1. Wallet is connected
2. Phantom extension added to Chrome

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Click on "Connect Wallet" on Send from section
2. Click on Phantom
3. Click on "Connect Wallet" on Send to section
4. Click on Phantom
5. Observe
6. Refresh the page
7. Click on "Connect Wallet" on Send to section
8. Click on Phantom
9. Click on "Connect Wallet" on Send from section
10. Click on Phantom
11. Observe

Actual result: User can not connect to Phantom both in Send from and Send to sections at the same time.

Expected result: User is able to connect to Phantom wallet in both Send from and Send to sections at the same time.

Attachment:

https://user-images.githubusercontent.com/91047061/222697135-ce83c07f-6fcc-487c-8b1a-b5a66d1f9908.mov

**Comment by tsadovska** [comment] 2023-05-05 11:47
Closing the ticket, because it is no longer reproducible. 
Checked on:

- https://wormhole-connect.netlify.app/
- https://mainnet--wormhole-connect.netlify.app/

Checked with following wallets:

- Metamask
- WalletConnect
- Phantom
- Solflare 
- Sui Wallet

**Closed by tsadovska** 2023-05-05 11:47 UTC
Labels: p2, wallet
