### ISSUE TITLE
[QA] Explorer link is not displayed when transaction is completed - BscScan

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2201] opened 2024-06-17 08:51 UTC
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] and https://preview.portalbridge.com/2c6f665417/ [Mainnet] with macOS Sonoma 14.4.1 and Google Chrome Version 125.0.6422.142 (Official Build) (arm64).

Steps:
1. Send 0.001 SOL from Solana (Phantom) to BSC (Rabby)
2. Click on "Approve and proceed with transaction" button
3. Click on "Claim" button
4. Click if link to BscScan is displayed in "Send to" section

Actual result: Link to BscScan is not displayed. 
Expected result: Link to BscScan is displayed

## Notes/ Attachments
* Linked issue: https://github.com/wormhole-foundation/wormhole-connect/issues/1078

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/fabd393e-d71f-47a8-9c6b-e775aeaf3817)

**Comment by tsadovska** [comment] 2024-06-20 14:59
Reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending asset to BSC with automatic route:
* AVAX from [Fuji](https://testnet.avascan.info/blockchain/c/tx/0x3185c217c2bd455ddf94a2c242b06dcdbdbbbdf5e713c242e1bceb609212f308) (MetaMask) to [BSC](https://testnet.bscscan.com/tx/0xafd35e20bf036d51476657e73aa2982bef116476e038f7d88cae52b70981bf89) (MetaMask), link to [Wormholescan](https://wormholescan.io/#/tx/0x3185c217c2bd455ddf94a2c242b06dcdbdbbbdf5e713c242e1bceb609212f308?network=TESTNET)
* FTM from [Fantom](https://testnet.ftmscan.com/tx/0x289c147ff0ca793387cef585d74f7cb55f910c2c3c6d2f28f0b8ddd11b16be89) (MetaMask) to [BSC](https://testnet.bscscan.com/tx/0x27074b8fb18dbe6888c8578f9b1c3869c233121ee81f3a7e96331cca5a9d77b6) (MetaMask), link to [Wormholescan](https://wormholescan.io/#/tx/0x289c147ff0ca793387cef585d74f7cb55f910c2c3c6d2f28f0b8ddd11b16be89?network=TESTNET)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/af2f6b8b-bec9-4f05-b7d4-2150a9bfb8aa)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ebae5a5d-b973-4ca3-97eb-bd4e4217a4f2)

**Comment by agodlevska** [comment] 2024-10-01 12:23
The issue is no longer relevant after the redesign, link on destination chain is no longer displayed.
Closing the ticket.

**Closed as not planned by agodlevska** 2024-10-01 12:23 UTC
Labels: p2
