### ISSUE TITLE
[QA] [Mainnet] Cannot change slider position when sending CELO from Celo

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2010] opened 2024-04-29 09:56 UTC
## Environment
Checked on [mainnet](https://wormhole-connect-mainnet.netlify.app/) with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.62 (Official Build) (arm64). 

```
{
  env: 'mainnet',
  "bridgeDefaults": {
    fromNetwork: 'celo',
    toNetwork: 'moonbeam',
    token: 'CELO',
  }
}
```

## Describe the current behavior in detail
Steps:
1. Open [wormhole-connect](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJAGNIHEYWIRcIybhnzFKESOhlIaFBsFhtcmIoDCAUQAyAeStgAviC9A)
2. Enter 1.4 in Amount field
3. Switch route to Manual and then change it back to Automatic
4. Change slider position

Actual result: Slider position cannot be changed. 
Expected result: Slider position can be changed. 

Reproducibility: 1/4

Error:
```
Uncaught (in promise) TypeError: Failed to fetch
    at getUsdVal (main-E6sKK0B5.js:484:653676)
    at getConversion (main-E6sKK0B5.js:484:653909)
    at async main-E6sKK0B5.js:524:19150
```

## Notes/ Attachments

[Link](https://github.com/wormhole-foundation/wormhole-connect/issues?q=is%3Aissue+is%3Aopen+cannot+change+slider+position) to similar issues.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/78f404c2-d345-4117-976d-dd753e8ff7f5

**Comment by AigaD** [comment] 2024-04-29 10:08
Tested from: [Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJAGNIHEYWIRcIybhnzFraNpQbBYbXJiKAwgFEAMgHkzYAL4g3QA#)

```
{
  env: 'mainnet',
  "bridgeDefaults": {
    fromNetwork: 'celo',
    toNetwork: 'fantom',
    token: 'CELO',
  }
}
```
Cannot change slider position for Native gas when sending CELO from Celo to Fantom or other networks

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/969c7566-ac41-4d57-ba42-51d7efb8be46

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/8a2aa571-1c2e-44da-8b01-3f1bb23bcc61

**Comment by tsadovska** [comment] 2024-05-10 11:05
Reproducible on https://wormhole-connect.netlify.app/ [Testnet] when sending CELO from Celo (MetaMask) to Moonbase (MetaMask). 

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/ba21295a-63e8-4847-abd1-3b6720628887

**Comment by agodlevska** [comment] 2024-07-25 12:54
The issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/.
User can change slider position when sending CELO from Celo to Moonbase, issue reproducibility: 0/10.
Closing the ticket.

Attachment:

https://github.com/user-attachments/assets/909b3e9e-a43d-4b08-a8fe-75963db91af6

**Closed as completed by agodlevska** 2024-07-25 12:54 UTC
Labels: p2
