### ISSUE TITLE
[QA] Transaction simulation failed: Blockhash not found, when sending SOL from Phantom wallet

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#152] opened 2023-03-06 15:49 UTC
Preconditions:
1. Phantom Wallet is connected at Sending from section
2. MetaMask wallet is connected at Sending to section
3. Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. Prepare to send 0.111 SOL from Solana to Goerli
2. Click "Approve and proceed with transaction"
3. Observe the pop-up message from Phantom extension
4. Click "Ignore warning, proceed anyway"
5. Observe

Actual result: Message "Phantom - RPC Error: failed to send transaction: Transaction simulation failed: Blockhash not found" is shown and transaction fails.

Expected result: Transaction completes.

Attachment:

https://user-images.githubusercontent.com/91047061/223159071-31da0430-9f65-4ea2-ade8-e905f312936e.mov

**Comment by tsadovska** [comment] 2023-05-19 13:25
Closing the ticket, because issue is not reproducible when Testmode is enabled in Phantom wallet and “Solana Devnet” is selected as Test Network. 

Transaction details:
1) SOL transfer from Solana (Phantom wallet) to Goerli (Metamask wallet):
[Solana Testnet tx](https://explorer.solana.com/tx/7jw3y7MNgHCvUsnwejb5KRpYgq5xZT9Y6r1QF3Te5iBPF3M6W29JiFDLnVcF5toUuYTiWEcV9JgCYjMrAy5BLbL?cluster=devnet)
[Goerli Testnet tx](https://goerli.etherscan.io/tx/0x2f32da4ba122438b3d1c3c25e2d46d3725d92340d5b65bad6e26166a116ea7ca)

2) SOL transfer from Solana (Phantom wallet) to Mumbai (Metamask wallet):
[Solana Testnet tx](https://explorer.solana.com/tx/KXixsBPL18mRQFaKNRDtg8JHQmABJM3vgWe1rMyobK2K62nEXZC1wZu11DBi9YHPTeyT7DCbuSrbwcR6Kv8DD9W?cluster=devnet)
[Mumbai Testnet tx](https://mumbai.polygonscan.com/tx/0x5b0aff434e230eedd572b717ab1c9e1225ad662d2e1018881ec88f0a72019093)


3) SOL transfer from Solana (Solflare wallet) to BSC (Metamask wallet):
[Solana Testnet tx](https://explorer.solana.com/tx/2mGGVejgRe7ThAWWPK28T1MP2Y8mzcDMer4pjBxB37ZWkMZqXSdpVkp9RTcjd74z2d5XJnoTVj8LiDQ7jAcMb3A8?cluster=devnet)
[BSC Testnet tx](https://testnet.bscscan.com/tx/0x67cc31f75422d196729e57bf5a290572eb47ef34ee0821ae9107e4179de95dfa)

**Closed as completed by tsadovska** 2023-05-19 13:25 UTC
Labels: p2
