### ISSUE TITLE
[QA]Token registration message is not shown if the token that need to be registered is not selected first for transaction

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#2083] opened 2024-05-15 07:49 UTC
Precondition:
none

Environment:
OS: macOS Sonoma 14.4.1
Browser: Chrome Version 121.0.6167.85

Tested from:
[Mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJGlhoOaaAGMAFpELEIuEZNwz5ismu74igsIbkxFeiAF8QLoA%3D%3D%3D#)

> {
  env: 'mainnet',
  "bridgeDefaults": {
    fromNetwork: 'avalanche',
    toNetwork: 'blast',
    token: '',
  }
}

Steps:
1. Select AVAX asset
2. Change it to USDC asset and enter the amount
3. Observe
4. Refresh the page
5. Select USDC asset
6. Observe

Actual result: If user changes asset to USDC message to register asset is not shown, but if selecting first the USDC asset after refreshing the page message "This token is not registered, you must [register](https://portalbridge.com/advanced-tools/#/register) it before you continue. Newly registered tokens will not have liquid markets." is shown

Expected result: Message "This token is not registered, you must [register](https://portalbridge.com/advanced-tools/#/register) it before you continue. Newly registered tokens will not have liquid markets." is shown every time a token needs to be registered

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/a60ac99b-6067-455d-a086-19cc6d24d25c

**Comment by agodlevska** [comment] 2024-09-24 08:04
The issue is no longer relevant after the redesign, the token cannot be selected if it is not registered.
Closing the ticket.

**Closed as not planned by agodlevska** 2024-09-24 08:04 UTC
Labels: p2
