### ISSUE TITLE
[QA] "Error in event handler: Error: write after end" appears in Console after opening the page

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1944] opened 2024-04-17 10:23 UTC
## Describe the current behavior in detail
Reproducible on:
* https://testnet.portalbridge.com/ed4e22522f/ [Testnet] (Portal Bridge: 0.2.12, Wormhole Connect: 0.3.4-beta.4-development)
* https://wormhole-connect.netlify.app/ [Testnet]
* https://wormhole-connect-mainnet.netlify.app/ [Mainnet]

Checked with macOS 14.4.1 (23E224) and Google Chrome Version 123.0.6312.107 (Official Build) (arm64).

Steps:
1. Open the page
2. Check Console tab

Actual result:  "Error in event handler: Error: write after end" appears in Console after opening the page.

```
Error in event handler: Error: write after end
  at <URL>
  at y.write (<URL>)
  at i.d (<URL>)
  at a.emit (<URL>)
  at U (<URL>)
  at F (<URL>)
  at B.push (<URL>)
  at i._onMessage (<URL>)
  at <URL>
```
Note: Issue is not reproducible after reloading the page. 

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/3694854b-c31b-4276-998d-fa0401a49574)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/70e42330-54c3-470f-900d-6fd113a77771

## What is the expected/desired behavior
The error does not appear in the Сonsole after opening the page.

**Comment by agodlevska** [comment] 2024-07-30 09:01
The issue is no longer reproducible on https://wormhole-connect.netlify.app/, https://wormhole-connect-mainnet.netlify.app/ and https://portalbridge.com/.
The error does not appear in the Сonsole after opening the page.
Closing the ticket.

Attachment:

https://github.com/user-attachments/assets/774d01de-1b5d-455f-8e01-408c5013f1c5

**Closed as completed by agodlevska** 2024-07-30 09:01 UTC
Labels: p2

**Comment by lennybeadle** [comment] 2024-08-20 00:22
what was the solution? Thanks
