### ISSUE TITLE
[QA][Fewcha Move] Transaction from Sui fails to start

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1178] opened 2023-10-27 14:22 UTC
Preconditions: 
1. Fewcha wallet connected at sending From section (Testnet enabled)
2. Phantom wallet connected at sending To section 
3. Console is open

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 118.0.5993.88

Tested from: https://wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.01 SUI from Sui to e.g. Solana
2. Click Approve and proceed with transaction
3. Observe

Actual result: Transaction shows as failed, reason `TypeError: Cannot read properties of undefined (reading 'startsWith')`

Expected result: transaction move to next screen and is completed

Attachment:
![Screenshot 2023-10-27 at 17 16 06](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4af924fd-ef66-4bc4-ae91-1d5e89d1ac66)
![Screenshot 2023-10-27 at 17 15 25](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/32f0eaca-4217-496f-9110-7a36561885ae)

**Comment by AigaD** [comment] 2024-01-18 10:19
Still reproducible.
Tested from: https://wormhole-connect.netlify.app/#
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/cdb14b6d-565a-43dc-84e8-c1df2e208095

**Comment by AigaD** [comment] 2024-01-26 08:38
Reproduced from: https://testnet.portal-bridge-ui.pages.dev/c0216a7edf/ and https://preview.portal-bridge-ui.pages.dev/c0216a7edf/ [Mainnet]
Transaction 0.01 SUI from Sui (Fewcha Move) to Solana (Phantom) fails to start.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f5e03e49-5f90-45e7-aba6-07caa7ac6ee5

**Comment by AigaD** [comment] 2024-01-31 08:18
Tested from: https://portalbridge.com/#
Transaction 0.01 SUI from Sui (Fewcha Move) to Solana (Phantom) is not moving forward to next screen, shows as loading.
Asset balance is deducted, but not received. Asset is received if user resumes transaction as described in this ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1054

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/714dc022-7d6f-4e6a-a3c7-94c8f37d545d


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0513023f-6039-4939-90cd-71ff81ffa40b

**Comment by AigaD** [comment] 2024-02-19 11:52
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transaction 0.01 SUI from Sui (Fewcha Move) to Optimism (Metamask) is not starting. Console shows `main.js:499 Error: Invalid Transaction digest`
Attachment:
<img width="1353" alt="Screenshot 2024-02-19 at 13 44 19" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c805736e-ec16-40e8-9b8b-670a9d2ecfdc">

**Comment by AigaD** [comment] 2024-03-01 13:21
Tested from: https://wormhole-connect-mainnet.netlify.app/#
Transaction SUI from Sui (Fewcha Move) to Solana (Phantom) is not starting, console shows `Error: Invalid Transaction digest at JsonRpcProvider.getTransactionBlock`
Attachment:

![Screenshot 2024-03-01 at 15 21 01](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/31314f26-6e91-4267-9942-7b26662db63e)

**Comment by AigaD** [comment] 2024-03-11 07:16
Tested from: https://preview.portalbridge.com/#
Transaction 0.001 SUI from Sui (Fewcha Move) to Avalanche (MetaMask) is not starting, error in console shown: `Error: Invalid Transaction digest`

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4640f5e6-e3c6-4b09-898a-6bbabf08d400

**Comment by tsadovska** [comment] 2024-05-03 13:12
Closing as duplicate of https://github.com/wormhole-foundation/wormhole-connect/issues/1054.

**Closed as completed by tsadovska** 2024-05-03 13:12 UTC
Labels: p1
