### ISSUE TITLE
[QA] "Error: Extension context invalidated" repeats every split second after Nightly extension is disabled

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1885] opened 2024-04-05 13:00 UTC
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome.

Steps:
1. Enable Nightly extension
2. Refresh https://wormhole-connect-mainnet.netlify.app/  and open Console
3. Disable Nightly extension
4. Check Errors in Console

Actual result: "Error: Extension context invalidated" repeats every split second.

```
Uncaught (in promise) Error: Extension context invalidated.
    at RT (contentScript.js:643:62915)
    at contentScript.js:643:63247
```

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/1e6cfd78-af8f-4988-bf24-734f9a0692ca

## What is the expected/desired behavior
Error does not appear so many times.

**Comment by agodlevska** [comment] 2024-07-08 13:16
Checked on https://wormhole-connect-mainnet.netlify.app/, https://wormhole-connect.netlify.app/ and  https://portalbridge.com/. 
The issue is no longer reproduced.
Closing the ticket. 

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/169661796/26895aa0-b0db-4737-9652-4e1752897782

**Closed as completed** 2024-07-08 13:35 UTC
Labels: p2
