### ISSUE TITLE
[QA] [Mainnet] Sometimes cannot change slider position when sending BNB from BSC to Polygon

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2008] opened 2024-04-29 08:11 UTC
## Environment
Checked on [mainnet](https://wormhole-connect-mainnet.netlify.app/) with macOS Sonoma 14.4.1 and Google Chrome Version 124.0.6367.62 (Official Build) (arm64). 

```
{
  env: 'mainnet',
  "bridgeDefaults": {
    fromNetwork: 'bsc',
    toNetwork: 'polygon',
    token: 'BNB',
  }
}
```

## Describe the current behavior in detail
Steps:
1. Open [wormhole-connect](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAEQBGAThgCYDmkAIpAGZoCuANrgM4mKgQIzCgHsUAOTwB3ERQDWiJGW4BjQsQi4Rk3DPmKADiI4BPWiOjrBYLXJiKAQuIdWwAXxBugA)
2. Enter 0.002 in Amount field
3. Switch route to Manual and then change it back to Automatic
4. Change slider position

Actual result: Slider position cannot be changed. 
Expected result: Slider position can be changed. 

Reproducibility: 1/7

## Notes/ Attachments

[Link](https://github.com/wormhole-foundation/wormhole-connect/issues?q=is%3Aissue+is%3Aopen+cannot+change+slider+position) to similar issues.

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/5baa5fb7-9eff-4b24-b5be-42c762ff7a54

**Comment by agodlevska** [comment] 2024-07-25 13:01
The issue is no longer reproducible on https://wormhole-connect-mainnet.netlify.app/.
User can change slider position when sending BNB from BSC to Polygon, issue reproducibility: 0/10.
Closing the ticket.

Attachment:

https://github.com/user-attachments/assets/d145e68e-1048-421d-90da-d1f9f829187a

**Closed as completed by agodlevska** 2024-07-25 13:01 UTC
Labels: p2
