### ISSUE TITLE
[QA] [Mainnet] Optimistic Etherscan link leads to invalid transaction hash result

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#1919] opened 2024-04-11 15:37 UTC
## Describe the current behavior in detail
Checked on https://wormhole-connect-mainnet.netlify.app/ [Mainnet] with macOS and Google Chrome. 

Steps:
1. Prepare to send 0.0004 ETH (Base) from Base (MetaMask) to Optimism (MetaMask)
2. Click "Approve and proceed with transaction" button
3. Click on "Optimistic Etherscan" link

Actual result: Optimistic Etherscan link opens result "Oops! An invalid Txn hash has been entered:
b194aa960b36c021da2b5c746fd43fe8267f1d41980bd935d75d79c7d5366fe2".

Correct link is: https://optimistic.etherscan.io/tx/0xb194aa960b36c021da2b5c746fd43fe8267f1d41980bd935d75d79c7d5366fe2

```
Error: invalid hash (argument="value", value="b194aa960b36c021da2b5c746fd43fe8267f1d41980bd935d75d79c7d5366fe2", code=INVALID_ARGUMENT, version=providers/5.7.2)
    at Logger.makeError (main-K_tZisHn.js:166:46729)
    at Logger.throwError (main-K_tZisHn.js:166:46862)
    at Logger.throwArgumentError (main-K_tZisHn.js:166:46923)
    at Formatter.hex (main-K_tZisHn.js:172:74447)
    at Formatter.hash (main-K_tZisHn.js:172:75118)
    at StaticJsonRpcProvider.<anonymous> (main-K_tZisHn.js:172:108186)
    at Generator.next (<anonymous>)
    at Hn (main-K_tZisHn.js:172:79192)
```

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/87486326-a2d7-4d62-ba03-8a8189b002af)

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/492b99a5-4ffb-4097-944f-21303728e1e0

## What is the expected/desired behavior
Transaction details page is opened when user clicks on Optimistic Etherscan link.

**Comment by tsadovska** [comment] 2024-04-30 15:47
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ when sending 0.001 ETH from Ethereum (MetaMask) to Optimism (MetaMask). 

Optimistic Etherscan link opens result "Oops! An invalid Txn hash has been entered:
43f487679f58961c1ad58f81488c1463da327f4c97bdb10dbfb2ed677956c5d0" https://optimistic.etherscan.io/tx/43f487679f58961c1ad58f81488c1463da327f4c97bdb10dbfb2ed677956c5d0 instead of https://optimistic.etherscan.io/tx/0x43f487679f58961c1ad58f81488c1463da327f4c97bdb10dbfb2ed677956c5d0. 

Send from tx: https://etherscan.io/tx/0x0a6df47b4ce8590ca6643b2d287c12e5ac9fba56165087d68a21206e978409cd
Link to Wormholescan: https://wormholescan.io/#/tx/0x0a6df47b4ce8590ca6643b2d287c12e5ac9fba56165087d68a21206e978409cd

Similar issue: https://github.com/wormhole-foundation/wormhole-connect/issues/1909.

**Comment by tsadovska** [comment] 2024-06-13 15:31
Issue is reproducible on https://wormhole-connect-mainnet.netlify.app/ when sending 0.0001 wstETH from Arbitrum (MetaMask) to Optimism (MetaMask). 

Optimistic Etherscan link opens result "Oops! An invalid Txn hash has been entered: e4faf5624e24e91c5f9de67c062e73db2aa7007583f33929413737b3c286bdf7" https://optimistic.etherscan.io/tx/e4faf5624e24e91c5f9de67c062e73db2aa7007583f33929413737b3c286bdf7 instead of https://optimistic.etherscan.io/tx/0xe4faf5624e24e91c5f9de67c062e73db2aa7007583f33929413737b3c286bdf7


* Send from tx: [Arbitrum Explorer](https://arbiscan.io/tx/0xd622385d4ac093f85bd51c7b37dd3a82cbf5ed5dd18c805eaa4e28300f8a856c)
* Link to [Wormholescan](https://wormholescan.io/#/tx/0xd622385d4ac093f85bd51c7b37dd3a82cbf5ed5dd18c805eaa4e28300f8a856c)

**Comment by agodlevska** [comment] 2024-06-17 09:09
Issue is reproducible on https://preview.portalbridge.com/2c6f665417/ when sending 0.0001 ETH from Base (MetaMask) to Optimism (MetaMask).

https://optimistic.etherscan.io/tx/6197b7d8dfd3583930336ac3aabb778a3d7e0f8021281f952f7f3d3591b2319b instead of https://optimistic.etherscan.io/tx/0x6197b7d8dfd3583930336ac3aabb778a3d7e0f8021281f952f7f3d3591b2319b

Send from tx: [Base](https://basescan.org/tx/0xd2c16b3d0a40229a0b053ff056726340072f0684582b025f2a9482443518e6fd)
Link to [Wormholescan](https://wormholescan.io/#/tx/0xd2c16b3d0a40229a0b053ff056726340072f0684582b025f2a9482443518e6fd)

**Comment by agodlevska** [comment] 2024-07-18 07:58
Issue is reproducible on https://preview.portalbridge.com/3365c86aff/ when sending 2 USDT from Base (MetaMask) to Optimism (MetaMask).

Send from tx: [Base](https://basescan.org/tx/0xa2ab55d45409cdd14fc29d7d21146d2dd2e2ab2e43a5c75505f1872b85228209)
Send to tx: [Invalid link](https://optimistic.etherscan.io/tx/7ac932e7a4e79ee549eb9069a933b5b92f063a9a489c9ae9d95c994daca73827) instead of [correct link](https://optimistic.etherscan.io/tx/0x7ac932e7a4e79ee549eb9069a933b5b92f063a9a489c9ae9d95c994daca73827)
Link to [Wormholescan](https://wormholescan.io/#/tx/0xa2ab55d45409cdd14fc29d7d21146d2dd2e2ab2e43a5c75505f1872b85228209)

**Comment by agodlevska** [comment] 2024-07-29 07:28
Issue is reproducible on https://preview.portalbridge.com/c6532d9b17/ when sending 0.00001 wstETH from Polygon (MetaMask) to Optimism (MetaMask).

Send from tx: [Polygon](https://polygonscan.com/tx/0x756f407f8f71c536ab6076a15ac7ddc363368a857ccae92b0d8abd4e5a8e9c1a)
Send to tx: [Invalid link](https://optimistic.etherscan.io/tx/e5fb2ac4a1d571dbd04be74cd949c6e9ed01c9e32a7d8e00c93ce3368f1284de) instead of [correct link](https://optimistic.etherscan.io/tx/0xe5fb2ac4a1d571dbd04be74cd949c6e9ed01c9e32a7d8e00c93ce3368f1284de)
Link to [Wormholescan](https://wormholescan.io/#/tx/0x756f407f8f71c536ab6076a15ac7ddc363368a857ccae92b0d8abd4e5a8e9c1a)

**Comment by agodlevska** [comment] 2024-08-15 06:54
Issue is reproducible on https://preview.portalbridge.com/321a610744/ when sending 0.00001 wstETH from Polygon (MetaMask) to Optimism (MetaMask).

- Send from tx: [Polygon](https://polygonscan.com/tx/0x532529620b3d745c3704a9a5d414cd7c9c53b42dab56f8f307f9ad3813e248ad)
- Send to tx: [Invalid link](https://optimistic.etherscan.io/tx/d136f52371be692325df95bb5d8209ee8a74cd64ec66651a1ade1b9f373442b5) instead of [correct link](https://optimistic.etherscan.io/tx/0xd136f52371be692325df95bb5d8209ee8a74cd64ec66651a1ade1b9f373442b5)
- Link to [Wormholescan](https://wormholescan.io/#/tx/0x532529620b3d745c3704a9a5d414cd7c9c53b42dab56f8f307f9ad3813e248ad)

**Comment by agodlevska** [comment] 2024-09-24 08:38
The issue is no longer relevant after the redesign, link on destination chain is no longer displayed.
Closing the ticket.

**Closed as not planned by agodlevska** 2024-09-24 08:38 UTC
Labels: p2, explorer
