### ISSUE TITLE
[Bug] Urgent Request for Fixing Terra Bridge Issue on Wormhole

### ISSUE THREAD

**Issue by KylerLizi** [wormhole-foundation/wormhole-connect#1432] opened 2024-01-08 06:48 UTC
Dear Wormhole Team,

I hope this message finds you well. I am writing to you as an ardent user of the Wormhole network, specifically concerning the Terra bridge functionality that has been out of service for several months. The inability to use this bridge has caused significant inconvenience and distress, as my funds have been immovably stuck within the system for an extended period.

In November, there were discussions on Discord indicating that a fix might be available by December. Additionally, I've observed corresponding code submissions on GitHub, which raised my hopes for a resolution. However, it has been over a month since these developments, and I am still unable to use the bridge on the frontend.

The prolonged unavailability of this service is more than just an inconvenience; it has tangible impacts on my financial situation. I understand that resolving such issues can be complex and time-consuming, but I implore the Wormhole team to prioritize this matter. The community's trust and your platform's credibility are at stake.

I kindly request a clear update on the situation. If the fix is imminent, please provide a definitive timeline. If there are unexpected delays or complications, being transparent about these challenges would be greatly appreciated. Your prompt and decisive action on this matter is crucial.

I remain hopeful and confident in your team's ability to resolve this issue. Your commitment to service excellence and user satisfaction has always set Wormhole apart. Please consider this request with the urgency it entails, as many of us rely on your services for our blockchain endeavors.

Thank you for your attention to this matter. I look forward to a positive resolution and continued use of Wormhole's services.

Best regards.

**Comment by tonyjin** [comment] 2024-02-01 01:09
Dupe of https://github.com/wormhole-foundation/wormhole/issues/3633, which is resolved

**Closed as completed by tonyjin** 2024-02-01 01:09 UTC
Labels: bug, integration-support
