### ISSUE TITLE
[QA][Testnet] Base Goerli balance is not loading

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1613] opened 2024-02-07 14:32 UTC
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 121.0.6167.85

Tested from: 
https://wormhole-connect.netlify.app/# - Tested NOK
https://wormhole-connect-mainnet.netlify.app/# - Tested OK

Steps:

1. Select Base Goerli
2. Click Assets
3. Observe

Actual result: Balance for Base Goerli is not loading

Expected result: Base Goerli balance is shown

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0683d4fa-549d-4130-9259-7a0e48ab2c4f

**Comment by tsadovska** [comment] 2024-02-12 08:47
Issue is no longer reproducible on https://wormhole-connect.netlify.app/ [Testnet]. Base Goerli balance is successfully loading.


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/146c806e-27c5-4e12-8829-6a1cda71d74e

Ticket is closed.

**Comment by AigaD** [comment] 2024-02-14 07:00
Re-opening.
Base Goerli balance for testnet is not loading.
Tested from: 
https://wormhole-connect.netlify.app/# - Tested NOK
https://wormhole-connect-mainnet.netlify.app/# - Tested OK
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/86591f69-7317-44c1-be06-f14951511b2d

**Comment by AigaD** [comment] 2024-02-19 15:11
Tested from: https://wormhole-connect.netlify.app/#
Tested OK. Closing the ticket.
Balance for Base Goerli loaded.
Attachment:

Uploading Screen Recording 2024-02-19 at 17.08.39.mov…

**Comment by AigaD** [comment] 2024-03-13 08:09
Re-opening the ticket.
Testnet Base Goerli balance is not loading.
Tested from: https://wormhole-connect.netlify.app/# - Tested NOK
https://wormhole-connect-mainnet.netlify.app/ - Tested OK

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/28ca8129-4e53-4473-9cf7-b403acd58c2a

**Comment by tsadovska** [comment] 2024-06-11 07:20
Base Goerli balance is not loading on https://wormhole-connect.netlify.app/ [Testnet]. Closing the issue, because Goerli is deprecated. See ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1623.

**Closed as not planned by tsadovska** 2024-06-11 07:20 UTC
Labels: p1
