### ISSUE TITLE
[QA][iOS] Connect Wallet list shows install Metamask, when app is already installed on the device

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#606] opened 2023-05-11 07:57 UTC
Preconditions: Metamask app installed to the device

Environment: iPhone 14, iOS 16.0, Safari

Tested from: https://wormhole-connect.netlify.app/#

Steps:
1. Click on Connect Wallet button
2. From the list choose Metamask
3. Observe

Actual result: Install Metamask is shown in the list, page to install it is opened although user has the Metamask app on the phone. After clicking on it Metamask wallet is still not connected.

Expected result: Metamask app gets connected to Wormhole-connect.

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/3d02d463-8cfa-4e02-a715-c5872c481755

**Comment by tsadovska** [comment] 2023-05-11 10:33
Issue is also reproducible on Samsung S20 (Android 12) with Chrome Version: 112.0.5672.76

**Comment by AigaD** [comment] 2023-10-03 10:05
Issue still reproducible. Tested from: https://wormhole-connect.netlify.app/#
Environment: iPhone 14, iOS 16.0
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0a9718a2-c299-4020-9d38-af61625eaa1d

**Comment by tsadovska** [comment] 2023-12-20 09:50
Issue is also reproducible with Keplr wallet. "Install Keplr" is shown on Wallets screen when Keplr application is installed on mobile. Checked on iPhone 11 Pro iOS 16.5.1, Google Chrome Version 114.0.5735.124 and Keplr version 1.1.31. 


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/a13571a1-0c4a-4414-91f8-2bb795ae1288

**Comment by tsadovska** [comment] 2024-08-13 17:22
Closing because MetaMask option is no longer displayed in the list and Cosmos Gateway route is not supported in the redesign.

**Closed as completed by tsadovska** 2024-08-13 17:22 UTC
Labels: p2
