### ISSUE TITLE
[QA] No bridge or swap route available for selected tokens for transactions from Arbitrum

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#979] opened 2023-09-14 14:50 UTC
Preconditions:
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://latest--wormhole-connect.netlify.app/#

Steps:
1. At sending From section select Arbitrum
2. At sending To section select any other Network
3. Select asset USDC / ETH
4. Observe

Actual result: Message "No bridge or swap route available for selected tokens" is shown

Expected result: Bridge ad swap routes are available for transaction from Arbitrum

Attachment:

<img width="1238" alt="Screenshot 2023-09-14 at 17 45 42" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/06edad96-f9f0-4544-b13b-69943bfb97fc">

<img width="1250" alt="Screenshot 2023-09-14 at 17 43 52" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c22df42b-464f-4d9d-96b9-a6123c540ae7">

<img width="1013" alt="Screenshot 2023-09-14 at 17 46 53" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/45dd6995-6819-4854-a620-59e8fc895e33">

**Comment by derpy-duck** [comment] 2023-09-14 19:02
This is intended - the token bridge on Arbitrum doesn't allow sending native ETH - so I disabled specifically transferring Arbitrum ETH

**Comment by AigaD** [comment] 2023-09-15 05:40
Changing the priority to P2 as per comment above

**Comment by AigaD** [comment] 2023-09-25 11:39
Tests from Arbitrum -> "No bridge or swap route available for selected tokens"
Tested from: https://deploy-preview-1015--wormhole-connect.netlify.app/#
Attachment:
<img width="1027" alt="Screenshot 2023-09-25 at 14 13 55" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/1a8fe8c4-2f28-4d2f-9307-0d0b67cbccc0">

**Comment by AigaD** [comment] 2023-09-26 12:49
Reproduced from: https://deploy-preview-1029--wormhole-connect.netlify.app/#
<img width="1118" alt="Screenshot 2023-09-26 at 15 49 03" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f9671a01-849e-4851-aa92-536430c34a90">

**Comment by tsadovska** [comment] 2023-10-04 17:55
Issue is reproducible on https://deploy-preview-1058--wormhole-connect-mainnet.netlify.app/ [Mainnet] when sending ETH (Arbitrum) from Arbitrum (Metamask) to Solana (Phantom).

**Comment by tsadovska** [comment] 2023-10-11 13:49
Closing the issue as per the comment above it is expected behavior that token bridge on Arbitrum doesn't allow sending ETH (Arbitrum):
> [derpy-duck](https://github.com/derpy-duck) commented [last month](https://github.com/wormhole-foundation/wormhole-connect/issues/979#issuecomment-1719986729)
This is intended - the token bridge on Arbitrum doesn't allow sending native ETH - so I disabled specifically transferring Arbitrum ETH

Scenario "Send USDC from Arbitrum Goerli (Metamask) to Goerli (Metamask)" - Tested OK:
* Send from tx: [Arbiscan](https://testnet.arbiscan.io/tx/0xfce9e06df5ccea8872ac7acbd22f7faf170e016ea9f2a2ada029ec1e3fd6aa0c)
* Send to tx: [Etherscan](https://goerli.etherscan.io/tx/0xd8b02a71bb236f4dc2309ee70ad61802e3f0fc281c8c6bbc469dc76fb6911887)

**Closed as completed by tsadovska** 2023-10-11 13:49 UTC
Labels: p2
