### ISSUE TITLE
[QA]Transaction shows as rejected is user does not confirm it on mobile in timely matter 

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1336] opened 2023-12-14 09:12 UTC
Preconditions:
Wallets at sending From and sending To sections are connected through WalletConnect -> Metamask app

Environment: Samsung Galaxy S22+, OS12
MacBook Pro, macOS Ventura 13.0.1, Chrome Version 119.0.6045.159

Tested from: https://wormhole-connect.netlify.app/#

Steps:
1. Prepare to send 0.01 USDC from Base Goerli to Fuji
2. Click Approve and Proceed with transaction
3. Click Switch network from mobile if option is shown
4. Click Approve for transaction submitted 
5. Do not press Confirm for the transaction for approximately 7min
6. Observe transaction on Desktop
7. Click Confirm on the mobile app

Actual result: On desktop message "Error with transfer, please try again", reason ` 'User rejected the transaction'` is shown after few minutes if Confirm is not pressed on mobile device. On mobile device after pressing Confirm transaction shows as success

Expected result: Transaction on desktop should not show Error with transfer if user has not Confirmed the transaction on mobile in timely matter

Attachment:

[Base Goerli scan](https://goerli.basescan.org/tx/0x00f4b68abbaef629350e946b27d764930b35a5365c424c2b9942fabad0ac9c4d)

![Screenshot 2023-12-14 at 10 39 27](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ad187f25-0b4e-4a7f-8fea-6384942a99dc)

![Screenshot_20231214-103904_MetaMask](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/ec9233c7-9921-4922-800a-10e25d23c7a6)

**Comment by tsadovska** [comment] 2024-03-01 15:11
Issue is reproducible with following scenario:
1. Open https://wormhole-connect.netlify.app/ on Desktop
2. Connect MetaMask wallets with QR Code through WalletConnect in "From" and "To" sections
3. Click "Approve and proceed with transaction" button
4. Check that confirm transaction pop-up is shown on mobile
5. Wait until warning "Error with transfer, please try again" is shown on Desktop
6. Click "Confirm" button on mobile
7. Check if transaction is started 

Actual result: Transaction is started, [FTMScan](https://testnet.ftmscan.com/tx/0x7c87c174e4214d7fb36104e864cd6f8f40eee81fe2a2f88385e86ab4e68fcc03).

**Comment by tsadovska** [comment] 2024-08-23 12:33
Closing as not a bug, error was shown because transaction was not approved in the timely manner.

**Closed as not planned by tsadovska** 2024-08-23 12:33 UTC
Labels: p1
