### ISSUE TITLE
[QA] "Pay with GLMR (one transaction)" missing Moonbase - Mumbai

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#409] opened 2023-04-24 12:36 UTC
Preconditions: Wallet is not connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 108.0.5359.98

Steps:
1. At sending From section select Moonbase Network
2. Select GLMR asset
3. At Sending To section select Mumbai
4. Enter the amount
5. Observe section Gas payment

Actual result: Pay with one transaction is missing. Only Pay with two transactions is present.

Expected result: Pay with one and pay with two transactions are shown.

Attachment:
Before:
<img width="479" alt="Screenshot_2023-04-24_at_15 30 02" src="https://user-images.githubusercontent.com/91047061/233997721-12a354f7-e973-480a-9987-2b9224cec600.png">

Now:

https://user-images.githubusercontent.com/91047061/233996802-f73c0999-9f85-46db-8347-75f608b33625.mov

**Comment by tsadovska** [comment] 2023-05-22 09:54
Closing the ticket because it is an expected behaviour that automatic method is disabled when swap rate information is not available.

**Closed by tsadovska** 2023-05-22 09:54 UTC
Labels: p1
