### ISSUE TITLE
[QA] Incorrect link to Etherscan is displayed when sending wstETH from a BSC Safe to an Eth EOA

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2287] opened 2024-07-25 09:37 UTC
## Describe the current behavior in detail
Checked on https://portalbridge.com/ [Mainnet] with macOS Sonoma 14.5 and Google Chrome Version 126.0.6478.183 (Official Build) (arm64). 

Steps:
1. Connect a BSC Safe multisig via WalletConnect
2. Initiate a transfer of wstETH from the BSC Safe to an Eth EOA. You may need to disconnect/reconnect wallets as the destination wallet is initially auto-populated with the same wallet as the source
3. Approve the Safe txn for approving token allowance
4. Approve the Safe txn for approving the transfer
5. Click on "Etherscan" link in "Send to" section

Actual result: Link opens https://etherscan.io/tx/0x52d7b538bba540e1159e6716bb624f4fa2c71df31f5e6f1763f06b6d07d92668 
Expected result: Link opens https://etherscan.io/tx/0x2c70e1e18b8e6804d593ac2a5ef862f67051ab9dfd71088c3b7cca818a5271bb

## Notes/ Attachments
* Send from tx: [BscScan](https://bscscan.com/tx/0x1de90326d2b5d9c647b2b96f26414f65cc133193ac21e005c3f09f3bde98bba0)
* Send to tx: [Incorrect link to Etherscan](https://etherscan.io/tx/0x52d7b538bba540e1159e6716bb624f4fa2c71df31f5e6f1763f06b6d07d92668) instead of [Correct link to Wormholescan](https://etherscan.io/tx/0x2c70e1e18b8e6804d593ac2a5ef862f67051ab9dfd71088c3b7cca818a5271bb) is displayed on Portal Bridge
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x1de90326d2b5d9c647b2b96f26414f65cc133193ac21e005c3f09f3bde98bba0)

https://github.com/user-attachments/assets/5b0d0003-4673-4f13-a40e-bc99fbf202e2

**Comment by agodlevska** [comment] 2024-10-02 16:27
The issue is no longer relevant after the redesign, link on source/destination chain is no longer displayed.
Closing the ticket.

**Closed as not planned by agodlevska** 2024-10-02 16:27 UTC
Labels: p2
