### ISSUE TITLE
[Enhancement] Action Button i.e. "Approve" Should Be White (not greyed out)

### ISSUE THREAD

**Issue by aakashthumaty** [wormhole-foundation/wormhole-connect#548] opened 2023-05-03 18:29 UTC
### Describe the issue in detail

The current main button Approve/Claim/etc. is greyed out, it looks like it cannot be clicked.

### What is the expected/desired behavior

 The action button should be white/match the UI of actionable buttons.

**Comment by M-Picco** [comment] 2023-05-09 16:15
Closing as duplicate of #549

**Closed as completed by M-Picco** 2023-05-09 16:15 UTC
